<a href="https://colab.research.google.com/github/Desireegit1/Desiree-Diaz-Python-Sprint-7-11/blob/main/Copia_de_SPRINT_8_DESIREE_DIAZ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **NIVEL1- Exercici 1:**

---


En aquest exercici has de realitzar una exploració inicial del DataFrame per respondre, com a mínim, a les següents preguntes:
•	» Quantes files i columnes té el dataset?
•	» Quin tipus de dades conté cada columna?
•	» Hi ha files duplicades?
•	» Les dades semblen coherents a primera vista?
•	» Detectes possibles problemes o inconsistències evidents?

In [ ]:
# Importar Pandas
import pandas as pd

In [ ]:
# Crear la función para cargar el Excel
def cargar_datos(archivo):
    df = pd.read_excel(archivo, header=3)
    return df

In [ ]:
# Cargar el archivo Excel
df = cargar_datos("sample_data/sprint8_complex.xlsx")

# Mostrar las primeras cinco filas // tienen caracteres incorrectos
display(df.head())

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1

In [ ]:
# 1. ANALIZAR LAS DIMENSIONES DEL DATASET

print("Número de filas:", df.shape[0])
print("Número de columnas:", df.shape[1])

Número de filas: 1007
Número de columnas: 20

In [ ]:
# 3. REVISAR LOS TIPOS DE DATOS DE CADA COLUMNA

print(df.dtypes)

Unnamed: 0                      int64
Nom                            object
Cognoms                        object
DNI                            object
País d'origen                  object
Ciutat                         object
Dia de Naixement              float64
Mes de Naixement              float64
Any de Naixement              float64
Gènere                         object
Salari mensual                 object
Fills                          object
No Fills                       object
Grup Professional              object
CÃ rrec                        object
Nombre_fills                  float64
Te_cotxe                       object
Km_anuals                     float64
Consum_mitja_L_100km          float64
Temperatura_mitjana_ciutat    float64
dtype: object

In [ ]:
# 4. DETECTAR FILAS DUPLICADAS

print("Número de filas duplicadas:", df.duplicated().sum())

Número de filas duplicadas: 0

5. COHERENCIA DE LOS DATOS

Los datos no parecen completamente coherentes.
Se observa  que algunas columnas tienen tipos de datos que no parecen adecuados para la información que contienen.
Hay diferentes formatos en los salarios y valores ausentes (NaN).Ademas algunas columnas tienen tipos de datos adecuados para la información que contienen.

In [ ]:
# 6. DETECTAR POSIBLES PROBLEMAS E INCONSISTENCIAS

# 1. Comprobar valores nulos
print("VALORES NULOS:")
print(df.isnull().sum())

# 2. Comprobar tipos de datos
print("\nTIPOS DE DATOS:")
print(df.dtypes)

# 3. Comprobar los formatos de los salarios
print("\nEJEMPLOS DE SALARIOS:")
print(df["Salari mensual"].head(10))

# 4. Comprobar los valores de género
print("\nVALORES DE GÉNERO:")
print(df["Gènere"].value_counts(dropna=False))

# 5. Comprobar las columnas del dataset
print("\nNOMBRES DE LAS COLUMNAS:")
print(df.columns.tolist())

VALORES NULOS:
Unnamed: 0                      0
Nom                             1
Cognoms                         1
DNI                             1
País d'origen                   1
Ciutat                          1
Dia de Naixement                1
Mes de Naixement                1
Any de Naixement                1
Gènere                         41
Salari mensual                  1
Fills                         588
No Fills                      422
Grup Professional               2
CÃ rrec                         2
Nombre_fills                  298
Te_cotxe                      349
Km_anuals                     692
Consum_mitja_L_100km          746
Temperatura_mitjana_ciutat     71
dtype: int64

TIPOS DE DATOS:
Unnamed: 0                      int64
Nom                            object
Cognoms                        object
DNI                            object
País d'origen                  object
Ciutat                         object
Dia de Naixement              float64
Mes de Naixement              float64
Any de Naixement              float64
Gènere                         object
Salari mensual                 object
Fills                          object
No Fills                       object
Grup Professional              object
CÃ rrec                        object
Nombre_fills                  float64
Te_cotxe                       object
Km_anuals                     float64
Consum_mitja_L_100km          float64
Temperatura_mitjana_ciutat    float64
dtype: object

EJEMPLOS DE SALARIOS:
0     1,469 â‚¬
1     2,718 â‚¬
2    1358 euros
3     1,478 â‚¬
4     1,284 â‚¬
5     2,069 â‚¬
6     2,349 â‚¬
7     2,855 â‚¬
8     1,338 â‚¬
9     1,450 â‚¬
Name: Salari mensual, dtype: object

VALORES DE GÉNERO:
Gènere
D       325
H       280
Dona    120
F       107
Home     52
NaN      41
M        34
A        24
NC       23
??        1
Name: count, dtype: int64

NOMBRES DE LAS COLUMNAS:
['Unnamed: 0', 'Nom', 'Cognoms', 'DNI', "País d'origen", 'Ciutat', 'Dia de Naixement', 'Mes de Naixement', 'Any de Naixement', 'Gènere', 'Salari mensual', 'Fills', 'No Fills', 'Grup Professional', 'CÃ\xa0rrec', 'Nombre_fills', 'Te_cotxe', 'Km_anuals', 'Consum_mitja_L_100km', 'Temperatura_mitjana_ciutat']

COMENTARIO FINAL - EJERCICIO 1

El dataset contiene 1007 filas y 20 columnas.No se han detectado filas completamente duplicadas. Los datos no son totalmente coherentes, ya que se observan valores nulos, errores de codificación y diferentes formatos en los salarios.
Algunas columnas presentan tipos de datos poco adecuados, como el salario (object) y las fechas de nacimiento (float64).

También aparece una posible columna innecesaria: Unnamed: 0.
En los siguientes ejercicios será necesario revisar y corregir estas inconsistencias para mejorar la calidad de los datos.

# **Nivel 1-Exercici 2:**

---

Validacions bàsiques de les dades i decisions d'eliminació
🎯 Objectiu: assegurar que les dades compleixen unes condicions mínimes de qualitat i determinar quines files poden continuar sent analitzades i quines s'han de descartar.
En aquest exercici hauràs de validar aspectes clau del dataset que són crítics en qualsevol context real d'anàlisi de dades, prenent decisions justificades sobre la validesa o eliminació de registres.

Aspectes a validar:

» Existeixen identificadors únics (DNI) per a cada persona?
» Què faràs amb les files duplicades o registres repetits?
» Hi ha valors obligatoris que falten o informació incoherent?
» Detectes formats incorrectes, errors de codificació o valors impossibles?

In [ ]:
# IDENTIFICAMO SPROBLEMAS DE CODIFICACIàON:

# Crear una copia del DataFrame original
df_limpio = df.copy()

# Mostrar los nombres de las columnas
print("NOMBRES DE LAS COLUMNAS:")
print(df_limpio.columns.tolist())

# Mostrar las primeras cinco filas
print("\nPRIMERAS CINCO FILAS:")
display(df_limpio.head())# S

NOMBRES DE LAS COLUMNAS:
['Unnamed: 0', 'Nom', 'Cognoms', 'DNI', "País d'origen", 'Ciutat', 'Dia de Naixement', 'Mes de Naixement', 'Any de Naixement', 'Gènere', 'Salari mensual', 'Fills', 'No Fills', 'Grup Professional', 'CÃ\xa0rrec', 'Nombre_fills', 'Te_cotxe', 'Km_anuals', 'Consum_mitja_L_100km', 'Temperatura_mitjana_ciutat']

PRIMERAS CINCO FILAS:

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1

In [ ]:
# PASO 1. CORREGIR ERRORES DE CODIFICACIÓN

def corregir_texto(texto):

    if isinstance(texto, str):
        try:
            return texto.encode("cp1252").decode("utf-8")
        except (UnicodeError, ValueError):
            return texto

    return texto


# Corregir los nombres de las columnas
df_limpio.columns = [
    corregir_texto(columna) for columna in df_limpio.columns
]

# Corregir los valores de texto
for columna in df_limpio.select_dtypes(include="object").columns:
    df_limpio[columna] = df_limpio[columna].map(corregir_texto)


# Mostrar los datos corregidos
display(df_limpio.head())

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 €",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 €",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,Tècnic IT,4.0,NaN,NaN,NaN,16.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 €",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 €",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1

In [ ]:
# PASO 2. DETECTAR Y ELIMINAR FILAS DUPLICADAS EXACTAS

# Contar filas antes de eliminar duplicados
filas_antes = len(df_limpio)

# Eliminar filas duplicadas
df_limpio = df_limpio.drop_duplicates()

# Contar filas después
filas_despues = len(df_limpio)

# Mostrar cuántas filas se han eliminado
print("Filas antes:", filas_antes)
print("Filas después:", filas_despues)
print("Filas eliminadas:", filas_antes - filas_despues)

Filas antes: 1007
Filas después: 1007
Filas eliminadas: 0

No hemos detectado filas duplicadas exactas de momento

In [ ]:
# PASO 3. COMPROBAR LA UNICIDAD DEL DNI

# Detectar registros con DNI duplicado
dni_duplicados = df_limpio[
    df_limpio["DNI"].notna() &
    df_limpio["DNI"].duplicated(keep=False)
]

# Mostrar los registros con DNI repetido
print("Registros con DNI duplicado:", len(dni_duplicados))

display(dni_duplicados.sort_values("DNI"))

Registros con DNI duplicado: 24

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
604,604,Laia,Navarro,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,"1,676 €",True,False,Grup A,Analista,1.0,True,50.0,NaN,14.2
250,250,Laia,Navarro Vila,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,1235 euros,True,True,Grup D,Analista junior,0.0,False,NaN,NaN,10.3
759,759,Oriol,Gómez,16618423V,Espanya,Sevilla,10.0,1.0,1968.0,NaN,"2,000 €",NaN,NaN,Grup A,Responsable de vendes,5.0,NaN,NaN,NaN,20.7
758,758,Oriol,Gómez,16618423V,Espanya,Màlaga,10.0,1.0,1968.0,H,1879 euros,True,NaN,Grup B,Data Analyst,4.0,False,NaN,NaN,NaN
754,754,Oriol,Gómez,16618423V,Espanya,Barcelona,10.0,1.0,1968.0,Home,2.358 €,True,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
654,654,Oriol,Gómez,16618423V,Espanya,Madrid,10.0,1.0,1968.0,Home,1731 euros,True,NaN,Grup B,Data analyst,4.0,NaN,NaN,NaN,NaN
692,692,Alexia,Pérez Díaz,49529438G,Espanya,Màlaga,12.0,10.0,1981.0,Dona,1663€,NaN,True,Grup C,Cap de projecte,NaN,True,80000.0,10.7,16.9
558,558,Alexia,Pérez Díaz,49529438G,Espanya,Màlaga,12.0,10.0,1981.0,Dona,"1,176 €",NaN,True,Grup A,Data Analyst,0.0,False,NaN,NaN,38.0
757,757,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786€,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
1004,1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786€,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
142,142,Marta,Ruiz,54013571W,Espanya,Palma,24.0,5.0,1982.0,H,"1,276 €",True,True,Grup A,Analista,0.0,False,NaN,NaN,15.7
89,89,Guillem,Pujol Costa,54013571W,Espanya,A Coruña,17.0,7.0,1983.0,D,1.574 €,True,NaN,Grup B,Project lead,4.0,False,NaN,NaN,14.6
40,1001,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 €",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
36,464,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 €",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
1003,1003,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 €,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
730,730,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 €,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
281,281,Xavier,Vidal,90585882A,Espanya,Alacant,2.0,7.0,1958.0,H,1179 euros,NaN,NaN,Grup A,Tècnic IT,0.0,True,63574.0,6.0,16.8
114,114,Pol,Serra,90585882A,Espanya,Girona,4.0,12.0,1960.0,H,"1,178 €",NaN,True,Grup A,Data Analyst,NaN,False,NaN,NaN,16.2
104,104,Oriol,Vila Casals,90585882A,Espanya,Madrid,30.0,9.0,1964.0,H,1987 euros,NaN,True,Grup B,Responsable de vendes,0.0,False,NaN,NaN,13.5
913,913,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,Dona,"1,000 €",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1000,1000,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,"1,073 €",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
25,25,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,993 €,NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1002,1002,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 €",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
372,372,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 €",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7

In [ ]:
# PASO 3.1. ANALIZAR LOS DNI DUPLICADOS

# Seleccionar los datos importantes para comparar
columnas = [
    "DNI",
    "Nom",
    "Cognoms",
    "Dia de Naixement",
    "Mes de Naixement",
    "Any de Naixement",
    "Gènere",
    "Ciutat",
    "Salari mensual"
]

# Mostrar los registros ordenados por DNI
display(
    dni_duplicados[columnas].sort_values("DNI")
)

,DNI,Nom,Cognoms,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Ciutat,Salari mensual
604,15909601K,Laia,Navarro,30.0,5.0,1958.0,D,Bilbao,"1,676 €"
250,15909601K,Laia,Navarro Vila,30.0,5.0,1958.0,D,Bilbao,1235 euros
759,16618423V,Oriol,Gómez,10.0,1.0,1968.0,NaN,Sevilla,"2,000 €"
758,16618423V,Oriol,Gómez,10.0,1.0,1968.0,H,Màlaga,1879 euros
754,16618423V,Oriol,Gómez,10.0,1.0,1968.0,Home,Barcelona,2.358 €
654,16618423V,Oriol,Gómez,10.0,1.0,1968.0,Home,Madrid,1731 euros
692,49529438G,Alexia,Pérez Díaz,12.0,10.0,1981.0,Dona,Màlaga,1663€
558,49529438G,Alexia,Pérez Díaz,12.0,10.0,1981.0,Dona,Màlaga,"1,176 €"
757,52590001R,Oriol,Ferrer,15.0,7.0,1973.0,D,Zaragoza,786€
1004,52590001R,Oriol,Ferrer,15.0,7.0,1973.0,D,Zaragoza,786€
142,54013571W,Marta,Ruiz,24.0,5.0,1982.0,H,Palma,"1,276 €"
89,54013571W,Guillem,Pujol Costa,17.0,7.0,1983.0,D,A Coruña,1.574 €
40,55283701C,Ida,Karlsen Eriksen,2.0,9.0,1992.0,D,Oslo,"1,614 €"
36,55283701C,Ida,Karlsen Eriksen,2.0,9.0,1992.0,D,Oslo,"1,614 €"
1003,55297384F,Claudia,Gil Ferrer,1.0,11.0,1981.0,H,València,1.789 €
730,55297384F,Claudia,Gil Ferrer,1.0,11.0,1981.0,H,València,1.789 €
281,90585882A,Xavier,Vidal,2.0,7.0,1958.0,H,Alacant,1179 euros
114,90585882A,Pol,Serra,4.0,12.0,1960.0,H,Girona,"1,178 €"
104,90585882A,Oriol,Vila Casals,30.0,9.0,1964.0,H,Madrid,1987 euros
913,90585882A,Sara,Serra,28.0,5.0,2002.0,Dona,Tarragona,"1,000 €"
1000,90585882A,Sara,Serra,28.0,5.0,2002.0,D,Tarragona,"1,073 €"
25,90585882A,Sara,Serra,28.0,5.0,2002.0,D,Tarragona,993 €
1002,97954019T,Alba,Muñoz,25.0,10.0,1983.0,D,Bilbao,"1,409 €"
372,97954019T,Alba,Muñoz,25.0,10.0,1983.0,D,Bilbao,"1,409 €"


Comparamos algunas columnas como: los nombres, apellidos, fechas de nacimiento, género y demás información asociada a cada DNI.

Si dos registros tienen el mismo DNI pero corresponden aparentemente a personas diferentes, existe una inconsistencia.

Tenemos los 24 registros correspondientes a 8 DNI duplicados

Coinciden el nombre, los apellidos y la fecha de nacimiento, pero existen diferencias en la ciudad, el género y el salario. Comparamos  diferencias entre DNI , así podremos distinguir los registros realmente equivalentes de aquellos que tienen información contradictoria.

Tampoco podemos determinar con seguridad qué registro debemos conservar.

In [ ]:
# PASO 3.6. GUARDAR LOS DNI DUPLICADOS EN OTRA TABLA

# Crear una tabla con todos los registros de DNI repetidos
df_revision = df_limpio[
    df_limpio["DNI"].duplicated(keep=False)
    & df_limpio["DNI"].notna()
].copy()

# Mostrar la tabla ordenada por DNI
display(df_revision.sort_values("DNI"))

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
604,604,Laia,Navarro,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,"1,676 €",True,False,Grup A,Analista,1.0,True,50.0,NaN,14.2
250,250,Laia,Navarro Vila,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,1235 euros,True,True,Grup D,Analista junior,0.0,False,NaN,NaN,10.3
759,759,Oriol,Gómez,16618423V,Espanya,Sevilla,10.0,1.0,1968.0,NaN,"2,000 €",NaN,NaN,Grup A,Responsable de vendes,5.0,NaN,NaN,NaN,20.7
758,758,Oriol,Gómez,16618423V,Espanya,Màlaga,10.0,1.0,1968.0,H,1879 euros,True,NaN,Grup B,Data Analyst,4.0,False,NaN,NaN,NaN
754,754,Oriol,Gómez,16618423V,Espanya,Barcelona,10.0,1.0,1968.0,Home,2.358 €,True,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
654,654,Oriol,Gómez,16618423V,Espanya,Madrid,10.0,1.0,1968.0,Home,1731 euros,True,NaN,Grup B,Data analyst,4.0,NaN,NaN,NaN,NaN
692,692,Alexia,Pérez Díaz,49529438G,Espanya,Màlaga,12.0,10.0,1981.0,Dona,1663€,NaN,True,Grup C,Cap de projecte,NaN,True,80000.0,10.7,16.9
558,558,Alexia,Pérez Díaz,49529438G,Espanya,Màlaga,12.0,10.0,1981.0,Dona,"1,176 €",NaN,True,Grup A,Data Analyst,0.0,False,NaN,NaN,38.0
757,757,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786€,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
1004,1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786€,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
142,142,Marta,Ruiz,54013571W,Espanya,Palma,24.0,5.0,1982.0,H,"1,276 €",True,True,Grup A,Analista,0.0,False,NaN,NaN,15.7
89,89,Guillem,Pujol Costa,54013571W,Espanya,A Coruña,17.0,7.0,1983.0,D,1.574 €,True,NaN,Grup B,Project lead,4.0,False,NaN,NaN,14.6
40,1001,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 €",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
36,464,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 €",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
1003,1003,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 €,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
730,730,Claudia,Gil Ferrer,55297384F,Espanya,València,1.0,11.0,1981.0,H,1.789 €,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
281,281,Xavier,Vidal,90585882A,Espanya,Alacant,2.0,7.0,1958.0,H,1179 euros,NaN,NaN,Grup A,Tècnic IT,0.0,True,63574.0,6.0,16.8
114,114,Pol,Serra,90585882A,Espanya,Girona,4.0,12.0,1960.0,H,"1,178 €",NaN,True,Grup A,Data Analyst,NaN,False,NaN,NaN,16.2
104,104,Oriol,Vila Casals,90585882A,Espanya,Madrid,30.0,9.0,1964.0,H,1987 euros,NaN,True,Grup B,Responsable de vendes,0.0,False,NaN,NaN,13.5
913,913,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,Dona,"1,000 €",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1000,1000,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,"1,073 €",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
25,25,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,993 €,NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1002,1002,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 €",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
372,372,Alba,Muñoz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 €",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7

In [ ]:
# PASO 3.2. MOSTRAR TODOS LOS DNI DUPLICADOS; para poder tomar decisiones,

# Mostrar la tabla completa
with pd.option_context("display.max_rows", None):
    display(dni_duplicados[columnas].sort_values("DNI"))

,DNI,Nom,Cognoms,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Ciutat,Salari mensual
604,15909601K,Laia,Navarro,30.0,5.0,1958.0,D,Bilbao,"1,676 €"
250,15909601K,Laia,Navarro Vila,30.0,5.0,1958.0,D,Bilbao,1235 euros
759,16618423V,Oriol,Gómez,10.0,1.0,1968.0,NaN,Sevilla,"2,000 €"
758,16618423V,Oriol,Gómez,10.0,1.0,1968.0,H,Màlaga,1879 euros
754,16618423V,Oriol,Gómez,10.0,1.0,1968.0,Home,Barcelona,2.358 €
654,16618423V,Oriol,Gómez,10.0,1.0,1968.0,Home,Madrid,1731 euros
692,49529438G,Alexia,Pérez Díaz,12.0,10.0,1981.0,Dona,Màlaga,1663€
558,49529438G,Alexia,Pérez Díaz,12.0,10.0,1981.0,Dona,Màlaga,"1,176 €"
757,52590001R,Oriol,Ferrer,15.0,7.0,1973.0,D,Zaragoza,786€
1004,52590001R,Oriol,Ferrer,15.0,7.0,1973.0,D,Zaragoza,786€
142,54013571W,Marta,Ruiz,24.0,5.0,1982.0,H,Palma,"1,276 €"
89,54013571W,Guillem,Pujol Costa,17.0,7.0,1983.0,D,A Coruña,1.574 €
40,55283701C,Ida,Karlsen Eriksen,2.0,9.0,1992.0,D,Oslo,"1,614 €"
36,55283701C,Ida,Karlsen Eriksen,2.0,9.0,1992.0,D,Oslo,"1,614 €"
1003,55297384F,Claudia,Gil Ferrer,1.0,11.0,1981.0,H,València,1.789 €
730,55297384F,Claudia,Gil Ferrer,1.0,11.0,1981.0,H,València,1.789 €
281,90585882A,Xavier,Vidal,2.0,7.0,1958.0,H,Alacant,1179 euros
114,90585882A,Pol,Serra,4.0,12.0,1960.0,H,Girona,"1,178 €"
104,90585882A,Oriol,Vila Casals,30.0,9.0,1964.0,H,Madrid,1987 euros
913,90585882A,Sara,Serra,28.0,5.0,2002.0,Dona,Tarragona,"1,000 €"
1000,90585882A,Sara,Serra,28.0,5.0,2002.0,D,Tarragona,"1,073 €"
25,90585882A,Sara,Serra,28.0,5.0,2002.0,D,Tarragona,993 €
1002,97954019T,Alba,Muñoz,25.0,10.0,1983.0,D,Bilbao,"1,409 €"
372,97954019T,Alba,Muñoz,25.0,10.0,1983.0,D,Bilbao,"1,409 €"

Los casos más graves son los DNI 54013571W y 90585882A, porque aparecen asociados a personas con nombres y fechas de nacimiento diferentes. Sin una fuente externa fiable, no podemos determinar a quién pertenece realmente cada DNI.

En los demás casos hay coincidencias de identidad, pero debemos comprobar si las diferencias de salario o ciudad son errores, actualizaciones o registros distintos.

Además, que dos filas coincidan en las nueve columnas mostradas no significa que sean duplicados exactos, porque el dataset tiene 20 columnas.

In [ ]:
# PASO 3.5. SEPARAR LOS DNI CONFLICTIVOS

# DNI que presentan información contradictoria
dni_conflictivos = [
    "15909601K",
    "16618423V",
    "49529438G",
    "54013571W",
    "90585882A"
]

# Guardar los registros conflictivos en otra tabla
df_descartados = df_limpio[
    df_limpio["DNI"].isin(dni_conflictivos)
].copy()

# Separar los registros conflictivos del DataFrame de análisis
df_limpio = df_limpio[
    ~df_limpio["DNI"].isin(dni_conflictivos)
].copy()

# Mostrar resultados
print("Registros separados:", len(df_descartados))
print("Registros restantes:", len(df_limpio))

display(df_descartados)

Registros separados: 16
Registros restantes: 991

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
25,25,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,993 €,NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
89,89,Guillem,Pujol Costa,54013571W,Espanya,A Coruña,17.0,7.0,1983.0,D,1.574 €,True,NaN,Grup B,Project lead,4.0,False,NaN,NaN,14.6
104,104,Oriol,Vila Casals,90585882A,Espanya,Madrid,30.0,9.0,1964.0,H,1987 euros,NaN,True,Grup B,Responsable de vendes,0.0,False,NaN,NaN,13.5
114,114,Pol,Serra,90585882A,Espanya,Girona,4.0,12.0,1960.0,H,"1,178 €",NaN,True,Grup A,Data Analyst,NaN,False,NaN,NaN,16.2
142,142,Marta,Ruiz,54013571W,Espanya,Palma,24.0,5.0,1982.0,H,"1,276 €",True,True,Grup A,Analista,0.0,False,NaN,NaN,15.7
250,250,Laia,Navarro Vila,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,1235 euros,True,True,Grup D,Analista junior,0.0,False,NaN,NaN,10.3
281,281,Xavier,Vidal,90585882A,Espanya,Alacant,2.0,7.0,1958.0,H,1179 euros,NaN,NaN,Grup A,Tècnic IT,0.0,True,63574.0,6.0,16.8
558,558,Alexia,Pérez Díaz,49529438G,Espanya,Màlaga,12.0,10.0,1981.0,Dona,"1,176 €",NaN,True,Grup A,Data Analyst,0.0,False,NaN,NaN,38.0
604,604,Laia,Navarro,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,"1,676 €",True,False,Grup A,Analista,1.0,True,50.0,NaN,14.2
654,654,Oriol,Gómez,16618423V,Espanya,Madrid,10.0,1.0,1968.0,Home,1731 euros,True,NaN,Grup B,Data analyst,4.0,NaN,NaN,NaN,NaN
692,692,Alexia,Pérez Díaz,49529438G,Espanya,Màlaga,12.0,10.0,1981.0,Dona,1663€,NaN,True,Grup C,Cap de projecte,NaN,True,80000.0,10.7,16.9
754,754,Oriol,Gómez,16618423V,Espanya,Barcelona,10.0,1.0,1968.0,Home,2.358 €,True,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
758,758,Oriol,Gómez,16618423V,Espanya,Màlaga,10.0,1.0,1968.0,H,1879 euros,True,NaN,Grup B,Data Analyst,4.0,False,NaN,NaN,NaN
759,759,Oriol,Gómez,16618423V,Espanya,Sevilla,10.0,1.0,1968.0,NaN,"2,000 €",NaN,NaN,Grup A,Responsable de vendes,5.0,NaN,NaN,NaN,20.7
913,913,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,Dona,"1,000 €",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1000,1000,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,"1,073 €",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8

Sabemos que hay cuatro DNI cuyos registros solo se diferenciaban en la columna Unnamed: 0.

Vamos a conservar un registro de cada uno y guardar los repetidos en df_descartados.

In [ ]:
# PASO 3.6. SEPARAR LOS DNI DUPLICADOS RESTANTES

# Identificar las repeticiones de DNI
duplicados = df_limpio["DNI"].notna() & df_limpio["DNI"].duplicated()

# Guardar las filas repetidas en la tabla de descartados
df_descartados = pd.concat([
    df_descartados,
    df_limpio[duplicados]
])

# Conservar un registro por DNI
df_limpio = df_limpio[~duplicados].copy()

# Mostrar resultados
print("Registros separados en total:", len(df_descartados))
print("Registros restantes:", len(df_limpio))
print("DNI duplicados restantes:",
      df_limpio["DNI"].dropna().duplicated().sum())

Registros separados en total: 20
Registros restantes: 987
DNI duplicados restantes: 0

In [ ]:
# PASO 4. COMPROBAR VALORES NULOS EN CAMPOS CLAVE

# Seleccionar los campos clave
campos_clave = ["Nom", "Cognoms", "DNI"]

# Contar valores nulos
print("VALORES NULOS EN CAMPOS CLAVE:")
print(df_limpio[campos_clave].isnull().sum())

# Mostrar registros con algún campo clave vacío
registros_incompletos = df_limpio[
    df_limpio[campos_clave].isnull().any(axis=1)
]

display(registros_incompletos)

VALORES NULOS EN CAMPOS CLAVE:
Nom        1
Cognoms    1
DNI        1
dtype: int64

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
1005,1005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


Como no tenemos información para identificar a la persona ni recuperar sus datos, está justificado excluir este registro del análisis.

In [ ]:
# PASO 4.1. SEPARAR REGISTROS IRRECUPERABLES

# Identificar filas sin información útil
columnas_datos = df_limpio.columns.drop("Unnamed: 0")

filas_vacias = df_limpio[columnas_datos].isnull().all(axis=1)

# Guardar los registros en la tabla de descartados
df_descartados = pd.concat([
    df_descartados,
    df_limpio[filas_vacias]
])

# Retirarlos del DataFrame de análisis
df_limpio = df_limpio[~filas_vacias].copy()

# Mostrar resultados
print("Registros irrecuperables:", filas_vacias.sum())
print("Total registros separados:", len(df_descartados))
print("Registros válidos restantes:", len(df_limpio))

Registros irrecuperables: 1
Total registros separados: 21
Registros válidos restantes: 986

**COMENTARIO FINAL - EJERCICIO 2**
Se han corregido los errores de codificación y acentuación.
No se han encontrado filas completamente duplicadas.
Se han detectado DNI repetidos y se ha analizado
la coherencia de la información asociada. Se han separado 20 registros por duplicidad de DNI, conservándolos en una tabla para su revisión.

También se ha identificado un registro completamente vacío, cuya información no puede recuperarse ni imputarse de manera fiable.
En total, se han separado 21 registros.
El DataFrame limpio contiene 986 filas.

Los registros separados se conservan para evitar la pérdida definitiva de información.

#**Exercici 3: Transformacions necessàries i preparació del dataset**


---


🎯 Objectiu: preparar el dataset perquè sigui coherent, analitzable i estructuralment correcte abans de realitzar qualsevol anàlisi descriptiva.
En aquest exercici hauràs d'aplicar transformacions bàsiques però essencials, orientades a millorar la qualitat de les dades i facilitar l'anàlisi posterior.

Aspectes a revisar i transformar:

» Els valors categòrics estan normalitzats i són consistents?
» Els valors nuls són coherents amb la informació disponible?
» Hi ha redundància de variables que pugui generar problemes analítics?
» Les variables contextuals (com temperatura, salari) estan completes i preparades per a l'anàlisi?

In [1]:

# ==================================================
# SPRINT 8 - NIVEL 1 - EJERCICIO 3
# APARTADO 1. NORMALIZAR VALORES CATEGÓRICOS
# ==================================================


# Crear una copia del DataFrame limpio
df_transformado = df_limpio.copy()


# 1. NORMALIZAR GÉNERO

df_transformado["Gènere"] = df_transformado["Gènere"].replace({
    "D": "Dona",
    "F": "Dona",
    "H": "Home",
    "M": "Home",
    "A": "Otros",
    "NC": pd.NA,
    "??": pd.NA
})

# 2. NORMALIZAR CARGOS

df_transformado["Càrrec"] = (
    df_transformado["Càrrec"]
    .str.strip()
    .str.lower()
    .str.title()
)

df_transformado["Càrrec"] = df_transformado["Càrrec"].replace({
    "Analyst": "Analista",
    "Admin.": "Administratiu",
    "Tècnic It": "Tècnic IT",
    "???": pd.NA
})


# 3. COMPROBAR RESULTADOS

print("GÉNEROS:")
print(df_transformado["Gènere"].value_counts(dropna=False))

print("\nCARGOS:")
print(df_transformado["Càrrec"].value_counts(dropna=False))

NameError: name 'df_limpio' is not defined

Comprobar que las personas con kilómetros anuales o consumo medio registrados disponen de coche y detectar los casos que tienen consumo, pero no kilometraje.

In [ ]:
# Comprobar que las personas con kilómetros anuales o consumo medio registrados disponen de coche y
#detectar los casos que tienen consumo, pero no kilometraje.

#PASO 2. COMPROBAR COHERENCIA ENTRE COCHE, KM Y CONSUMO

# Personas con kilómetros o consumo, pero sin coche confirmado
sin_coche = df_transformado[
    (df_transformado["Km_anuals"].notna() |
     df_transformado["Consum_mitja_L_100km"].notna())
    & (df_transformado["Te_cotxe"] != True)
]

# Personas con consumo, pero sin kilómetros
sin_km = df_transformado[
    df_transformado["Consum_mitja_L_100km"].notna()
    & df_transformado["Km_anuals"].isna()
]

# Mostrar resultados
print("Registros con datos de vehículo sin coche confirmado:", len(sin_coche))
print("Registros con consumo pero sin kilómetros:", len(sin_km))

display(sin_coche[["Te_cotxe", "Km_anuals", "Consum_mitja_L_100km"]])
display(sin_km[["Te_cotxe", "Km_anuals", "Consum_mitja_L_100km"]])

Registros con datos de vehículo sin coche confirmado: 4
Registros con consumo pero sin kilómetros: 2

    Te_cotxe  Km_anuals  Consum_mitja_L_100km
270    False        0.0                   NaN
698    False        0.0                   NaN
743    False        0.0                   NaN
922    False        0.0                   NaN

   Te_cotxe  Km_anuals  Consum_mitja_L_100km
4      True        NaN                  11.8
60     True        NaN                  25.0

In [ ]:
# PASO 2.1. VALIDAR COCHE, KILOMETRAJE Y CONSUMO

# Comprobar si hay kilómetros positivos o consumo sin coche
incoherencias = df_transformado[
    ((df_transformado["Km_anuals"] > 0) |
     df_transformado["Consum_mitja_L_100km"].notna())
    & (df_transformado["Te_cotxe"] != True)
]

print("Incoherencias reales de coche:", len(incoherencias))

# Comprobar consumo sin kilometraje
sin_km = df_transformado[
    df_transformado["Consum_mitja_L_100km"].notna()
    & df_transformado["Km_anuals"].isna()
]

print("Consumo sin kilometraje:", len(sin_km))

Incoherencias reales de coche: 0
Consumo sin kilometraje: 2

In [ ]:
# PASO 3. COMPROBAR Y CORREGIR LA COHERENCIA DE LOS HIJOS

# Detectar incoherencias
incoherencias = (
    (df_transformado["Nombre_fills"] > 0) &
    (df_transformado["Fills"] != True)
)

print("Incoherencias detectadas:", incoherencias.sum())

# Corregir utilizando el número de hijos
df_transformado.loc[incoherencias, "Fills"] = True
df_transformado.loc[incoherencias, "No Fills"] = False

# Comprobar resultados
print("Incoherencias restantes:",
      ((df_transformado["Nombre_fills"] > 0) &
       (df_transformado["Fills"] != True)).sum())

Incoherencias detectadas: 14
Incoherencias restantes: 0

Comprobamos si hay personas que sabemos que tienen hijos, pero cuyo número exacto desconocemos. No podemos asignarles un número sin información suficiente.

In [ ]:
# PASO 3.2. REVISAR HIJOS SIN NÚMERO REGISTRADO

# Personas que tienen hijos, pero no consta cuántos
sin_numero = df_transformado[
    (df_transformado["Fills"] == True) &
    (df_transformado["Nombre_fills"].isna())
]

print("Personas con hijos, pero sin número registrado:", len(sin_numero))

display(sin_numero[["Fills", "No Fills", "Nombre_fills"]])

Personas con hijos, pero sin número registrado: 3

    Fills No Fills  Nombre_fills
976  True     True           NaN
983  True     True           NaN
991  True     True           NaN

In [ ]:
# PASO 3.3. UNIFICAR LA INFORMACIÓN SOBRE HIJOS

# Identificar personas sin hijos y sin número registrado
sin_hijos = (
    (df_transformado["No Fills"] == True) &
    (df_transformado["Fills"] != True) &
    (df_transformado["Nombre_fills"].isna())
)

# Completar con 0 cuando sabemos que no tienen hijos
df_transformado.loc[sin_hijos, "Nombre_fills"] = 0

# Eliminar las dos columnas redundantes
df_transformado = df_transformado.drop(
    columns=["Fills", "No Fills"]
)

# Comprobar resultados
print("Valores nulos restantes:",
      df_transformado["Nombre_fills"].isna().sum())

display(df_transformado[["Nombre_fills"]].head(10))

Valores nulos restantes: 33

   Nombre_fills
0           3.0
1           0.0
2           4.0
3           2.0
4           0.0
5           0.0
6           0.0
7           4.0
8           0.0
9           4.0

Se ha unificado la información sobre hijos en Nombre_fills. Se ha asignado 0 cuando consta que la persona no tiene hijos. Los casos contradictorios se mantienen como nulos porque es posible determinar el número de hijos con fiabilidad. Se
 eliminan Fills y No Fills para evitar redundancias.

In [ ]:
# PASO 4. REVISAR TEMPERATURAS NULAS

print("Temperaturas nulas:",
      df_transformado["Temperatura_mitjana_ciutat"].isna().sum())

# Mostrar las ciudades de los registros sin temperatura
sin_temperatura = df_transformado[
    df_transformado["Temperatura_mitjana_ciutat"].isna()
]

print("\nCiudades con temperaturas faltantes:")
print(sin_temperatura["Ciutat"].value_counts())

Temperaturas nulas: 67

Ciudades con temperaturas faltantes:
Ciutat
València                      7
Màlaga                        6
Murcia                        6
Palma                         6
Alacant                       4
Girona                        4
Bilbao                        4
Zaragoza                      3
Barcelona                     3
Tarragona                     2
Sevilla                       2
Lyon                          2
Las Palmas de Gran Canaria    2
A Coruña                      2
Firenze                       1
Venezia                       1
Stavanger                     1
Valladolid                    1
Paris                         1
München                       1
Toulouse                      1
Madrid                        1
Marseille                     1
Frankfurt                     1
Bordeaux                      1
Torino                        1
Köln                          1
Desconeguda                   1
Name: count, dtype: int64

Utilizaremos la temperatura media de cada ciudad. Si alguna ciudad no tiene ninguna temperatura registrada, utilizaremos la media general del dataset.

In [ ]:
# PASO 4.1. IMPUTAR TEMPERATURAS FALTANTES

# Calcular la temperatura media de cada ciudad
media_ciudad = df_transformado.groupby("Ciutat")["Temperatura_mitjana_ciutat"].transform("mean")

# Rellenar los valores nulos con la media de su ciudad
df_transformado["Temperatura_mitjana_ciutat"] = (
    df_transformado["Temperatura_mitjana_ciutat"].fillna(media_ciudad)
)

# Si todavía quedan nulos, utilizar la media general
media_general = df_transformado["Temperatura_mitjana_ciutat"].mean()

df_transformado["Temperatura_mitjana_ciutat"] = (
    df_transformado["Temperatura_mitjana_ciutat"].fillna(media_general)
)

# Comprobar resultados
print("Temperaturas nulas restantes:",
      df_transformado["Temperatura_mitjana_ciutat"].isna().sum())

Temperaturas nulas restantes: 0

Se han detectado 67 temperaturas nulas. Se imputan utilizando la temperatura media de cada ciudad. Cuando no hay datos suficientes de una ciudad, se utiliza la media general del dataset. Se conservan las temperaturas originales disponibles.

In [ ]:
# PASO 5. REVISAR LOS SALARIOS

# Comprobar salarios nulos
print("Salarios nulos:",
      df_transformado["Salari mensual"].isna().sum())

# Mostrar una muestra de los salarios
print("\nEjemplos de salarios:")
print(df_transformado["Salari mensual"].head(10))

Salarios nulos: 0

Ejemplos de salarios:
0       1,469 €
1       2,718 €
2    1358 euros
3       1,478 €
4       1,284 €
5       2,069 €
6       2,349 €
7       2,855 €
8       1,338 €
9       1,450 €
Name: Salari mensual, dtype: object

In [ ]:
# PASO 5.1. NORMALIZAR LOS SALARIOS

# Recuperar los salarios originales
salarios = df_limpio["Salari mensual"].copy()

# Limpiar símbolos y separadores de miles
salarios = (
    salarios.astype("string")
    .str.lower()
    .str.replace("euros", "", regex=False)
    .str.replace("€", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace(".", "", regex=False)
    .str.strip()
)

# Convertir los salarios a números
df_transformado["Salari mensual"] = pd.to_numeric(
    salarios, errors="coerce"
)

# Comprobar resultados con punto de miles
print("Salarios nulos:",
      df_transformado["Salari mensual"].isna().sum())

display(
    df_transformado[["Salari mensual"]].head(10)
    .style.format({"Salari mensual": "{:,.0f} €"}, thousands=".", decimal=",")
)

Salarios nulos: 37

In [ ]:
# PASO 5.2. REVISAR SALARIOS NO CONVERTIDOS

# Identificar los salarios que no se han podido convertir
salarios_revisar = df_transformado[
    df_transformado["Salari mensual"].isna()
]

# Mostrar los valores originales y los datos asociados
display(df_limpio.loc[
    salarios_revisar.index,
    ["Salari mensual", "Càrrec", "Grup Professional"]
])

      Salari mensual                 Càrrec Grup Professional
14    mil vuit-cents        Analista junior            Grup A
39           dos mil         Senior analyst            Grup A
93               n/d           Data Analyst            Grup A
109   mil vuit-cents          Administratiu            Grup B
146              n/d        Analista junior            Grup A
159              n/d        Cap de Projecte            Grup A
166   mil vuit-cents           Data Analyst            Grup A
181          dos mil          Administratiu            Grup B
206   mil vuit-cents              Tècnic IT            Grup A
254              n/d         Senior analyst            Grup A
291              n/d         Senior analyst            Grup C
307              n/d               Analista            Grup C
339         tres mil           Data Analyst            Grup A
359   mil vuit-cents              Tècnic IT            Grup B
384              n/d           Data Analyst            Grup B
422   mil vuit-cents              Tècnic IT            Grup A
428         tres mil        Analista junior            Grup A
446              n/d              Tècnic IT            Grup A
458          dos mil               Analista            Grup B
472          dos mil  Responsable de vendes            Grup B
527          dos mil  Responsable de vendes            Grup A
546   mil vuit-cents  Responsable de vendes            Grup B
567         tres mil              Tècnic IT            Grup A
648   mil vuit-cents           Data Analyst            Grup B
656         tres mil           Data Analyst            Grup A
725   mil vuit-cents           Data Analyst            Grup B
749         tres mil         Senior analyst            Grup A
860              n/d              Tècnic IT            Grup A
875              n/d        Cap de projecte            Grup A
917              n/d         Senior analyst            Grup C
945          dos mil         Senior analyst            Grup C
953              n/d         Senior analyst            Grup A
955              n/d        Cap de Projecte            Grup A
956              n/d        Cap de projecte            Grup A
982          dos mil  Responsable de vendes            Grup B
994         tres mil         Senior analyst            Grup A
1006           molts                    ???                 Z

In [ ]:
# PASO 5.3. RECUPERAR SALARIOS ESCRITOS EN TEXTO

# Convertir los salarios expresados en palabras
equivalencias = {
    "mil vuit-cents": 1800,
    "dos mil": 2000,
    "tres mil": 3000
}

# Recuperar los salarios originales
salarios_texto = df_limpio["Salari mensual"].str.strip().str.lower()

# Sustituir los valores que podemos recuperar
salarios_recuperados = salarios_texto.map(equivalencias)

# Completar únicamente los salarios que quedaron nulos
df_transformado["Salari mensual"] = (
    df_transformado["Salari mensual"].fillna(salarios_recuperados)
)

# Comprobar resultados
print("Salarios nulos restantes:",
      df_transformado["Salari mensual"].isna().sum())

Salarios nulos restantes: 15

Se han detectado salarios escritos en palabras y
valores no disponibles (n/d). Los salarios expresados en palabras se convierten
a números porque conocemos su importe exacto. Los valores n/d se mantienen como nulos para imputarlos posteriormente con un criterio analítico.

Utilizaremos la mediana salarial del mismo cargo y grupo profesional. Es un criterio razonable porque compara trabajadores con características laborales similares y reduce la influencia de salarios extremos.

In [ ]:
# PASO 5.4. IMPUTAR LOS SALARIOS FALTANTES

# Convertir los salarios a tipo decimal
df_transformado["Salari mensual"] = (
    df_transformado["Salari mensual"].astype("float64")
)

# Contar salarios nulos antes
print("Salarios nulos antes:",
      df_transformado["Salari mensual"].isna().sum())

# Calcular la mediana por cargo y grupo profesional
mediana_salario = df_transformado.groupby(
    ["Càrrec", "Grup Professional"]
)["Salari mensual"].transform("median")

# Completar los salarios faltantes
df_transformado["Salari mensual"] = (
    df_transformado["Salari mensual"].fillna(mediana_salario)
)

# Comprobar resultados
print("Salarios nulos después:",
      df_transformado["Salari mensual"].isna().sum())

Salarios nulos antes: 15
Salarios nulos después: 1

Se han recuperado 22 salarios escritos en palabras, convirtiéndolos a valores numéricos.

Los 14 salarios faltantes se han imputado utilizando la mediana salarial de trabajadores con el mismo cargo y grupo profesional. Este criterio permite estimar los salarios a partir de empleados con características laborales similares y reduce la influencia de valores extremos.

Después de la imputación, no quedan salarios nulos en el dataset de análisis.

In [ ]:
# PASO 5.5. REVISAR EL REGISTRO IRRECUPERABLE

# Recuperar el registro original para revisarlo
registro_1006 = df_limpio.loc[[1006]]

# Mostrar toda su información
display(registro_1006)

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
1006,1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

In [ ]:
# PASO 5.6. SEPARAR EL REGISTRO IRRECUPERABLE

# Guardar el registro en descartados si todavía no está
if 1006 not in df_descartados.index:
    df_descartados = pd.concat([
        df_descartados,
        registro_1006
    ])

# Retirarlo del DataFrame de análisis
df_transformado = df_transformado.drop(
    index=1006, errors="ignore"
)

# Comprobar resultados
print("Registros separados:", len(df_descartados))
print("Registros válidos:", len(df_transformado))
print("Salarios nulos:",
      df_transformado["Salari mensual"].isna().sum())

Registros separados: 22
Registros válidos: 985
Salarios nulos: 0

In [ ]:
# ==================================================
# PASO 6. COMPROBACIÓN FINAL DEL DATASET
# ==================================================

# 1. Comprobar dimensiones
print("Dimensiones:", df_transformado.shape)

# 2. Comprobar DNI duplicados
print("DNI duplicados:",
      df_transformado["DNI"].duplicated().sum())

# 3. Comprobar valores nulos
print("\nVALORES NULOS:")
print(df_transformado[
    ["Nombre_fills", "Km_anuals",
     "Consum_mitja_L_100km",
     "Temperatura_mitjana_ciutat",
     "Salari mensual"]
].isna().sum())

# 4. Comprobar tipo de dato del salario
print("\nTIPO DE DATO DEL SALARIO:")
print(df_transformado["Salari mensual"].dtype)

# 5. Comprobar columnas redundantes
print("\nCOLUMNAS REDUNDANTES:")
print([col for col in ["Fills", "No Fills"]
       if col in df_transformado.columns])

# 6. Comprobar registros separados
print("\nREGISTROS:")
print("Registros válidos:", len(df_transformado))
print("Registros separados:", len(df_descartados))
print("Registro 1006 conservado:",
      1006 in df_descartados.index)

Dimensiones: (985, 18)
DNI duplicados: 0

VALORES NULOS:
Nombre_fills                   32
Km_anuals                     675
Consum_mitja_L_100km          728
Temperatura_mitjana_ciutat      0
Salari mensual                  0
dtype: int64

TIPO DE DATO DEL SALARIO:
float64

COLUMNAS REDUNDANTES:
[]

REGISTROS:
Registros válidos: 985
Registros separados: 22
Registro 1006 conservado: True

### Conclusión del ejercicio 3

Se han realizado las transformaciones necesarias para mejorar la calidad, coherencia y estructura del dataset.

Se han normalizado las categorías de género y cargo, unificando los valores equivalentes y clasificando como nulos los valores desconocidos o no interpretables.

Se ha comprobado la coherencia entre la disponibilidad de coche, el kilometraje anual y el consumo medio. Los datos faltantes que no podían deducirse de forma fiable se han mantenido como nulos.

Se ha revisado la información sobre hijos, corrigiendo las inconsistencias detectadas y unificando los datos en la columna Nombre_fills. Se han eliminado las columnas redundantes Fills y No Fills.

Se han imputado las 67 temperaturas faltantes utilizando la media de cada ciudad y, cuando no había información suficiente, la media general.

Los salarios se han convertido a formato numérico, recuperando 22 importes escritos en palabras e imputando los 14 salarios faltantes mediante la mediana de trabajadores con el mismo cargo y grupo profesional.

Se ha identificado el registro 1006, que contenía información ficticia e incoherente, como un DNI no válido, una fecha de nacimiento imposible y un salario no interpretable. Este registro se ha conservado en df_descartados y se ha retirado del análisis sin perder su información original.

El dataset final contiene 985 registros y 18 columnas, sin DNI duplicados, salarios nulos, temperaturas faltantes ni columnas redundantes.

Se mantienen 32 valores nulos en Nombre_fills, 675 en Km_anuals y 728 en Consum_mitja_L_100km, porque no existe información suficiente para imputarlos de forma fiable.

El dataset queda preparado para realizar los análisis descriptivos del ejercicio 4.

**Exercici 4: Primeres anàlisis descriptives**

---


🎯 Objectiu: obtenir una primera visió global del dataset un cop s'han aplicat les transformacions bàsiques,
 mitjançant estadístiques descriptives i comparacions simples entre grups rellevants.
 Aspectes a revisar i analitzar:

» Construir taules resum descriptives.
» Fer comparacions bàsiques entre grups rellevants.
Concretament, hauràs de:

» Construir taules resum descriptives de salaris com una taula resum que permeti veure el sou mig, medià, mínim i màxim per Gènere. Ordena la taula en funció del sou mig.
» Crear una taula resum amb el salari mig per gènere (files) i país d'origen (columnes). Afegeix-hi les mitjanes als marges de la taula. Aplica format condicional a la taula per veure en un color més intens els valors més elevats.

In [ ]:
# ==================================================
# SPRINT 8 - NIVEL 1 - EJERCICIO 4
# PASO 1. ESTADÍSTICAS SALARIALES POR GÉNERO
# ==================================================

# Calcular media, mediana, mínimo y máximo por género
tabla_salarios = (
    df_transformado.groupby("Gènere")["Salari mensual"]
    .agg(
        Media="mean",
        Mediana="median",
        Mínimo="min",
        Máximo="max"
    )
    .sort_values("Media", ascending=False)
)

# Mostrar la tabla con dos decimales y símbolo de euro
display(tabla_salarios.style.format("{:,.2f} €"))

Se ha elaborado una tabla descriptiva de salarios por género, calculando la media, mediana, mínimo y máximo.

Los resultados se han ordenado de mayor a menor salario medio. El grupo Home presenta el salario medio más elevado (1.696,43 €), seguido de Otros (1.690,60 €) y Dona (1.481,22 €).

Estas diferencias son descriptivas y no permiten concluir por sí solas que exista una desigualdad salarial atribuible al género, ya que también pueden influir el cargo, el grupo profesional y la composición de cada grupo.

In [ ]:
# ==================================================
# SPRINT 8 - NIVEL 1 - EJERCICIO 4
# PASO 2. SALARIO MEDIO POR GÉNERO Y PAÍS
# ==================================================

# Crear tabla dinámica con medias en los márgenes
tabla_paises = pd.pivot_table(
    df_transformado,
    values="Salari mensual",
    index="Gènere",
    columns="País d'origen",
    aggfunc="mean",
    margins=True,
    margins_name="Media general"
)

# Mostrar con formato condicional y símbolo de euro
display(
    tabla_paises.style
    .background_gradient(cmap="Blues", axis=None)
    .format("{:,.2f} €", thousands=".", decimal=",", na_rep="-")
)

Se ha creado una tabla dinámica que muestra el salario medio por género y país de origen, incluyendo las medias en los márgenes.

Se ha aplicado un formato condicional en tonos azules, donde los colores más intensos representan salarios medios más elevados.

Los resultados muestran diferencias salariales entre géneros y países. La media general es de 1.570,14 €. Estas diferencias se describen sin establecer conclusiones causales.

In [ ]:
# PASO 3. EXTRA - COMPARACIÓN SALARIAL EN PORCENTAJES

# Calcular la media salarial general
media_general = df_transformado["Salari mensual"].mean()

# Crear tabla de comparación
tabla_porcentajes = tabla_salarios[["Media"]].copy()

# Calcular diferencia porcentual respecto a la media general
tabla_porcentajes["Diferencia %"] = (
    (tabla_porcentajes["Media"] / media_general - 1) * 100
)

# Mostrar resultados
display(
    tabla_porcentajes.style.format({
        "Media": "{:,.2f} €",
        "Diferencia %": "{:+.2f} %"
    }, thousands=".", decimal=",")
)

Se ha realizado una comparación porcentual de los salarios medios por género respecto a la media salarial general.

Los resultados muestran que el salario medio de Home es un 8,38 % superior a la media general, el de Otros un 8,01 % superior y el de Dona un 5,37 % inferior.

Mientras que los valores absolutos muestran las diferencias en euros, los porcentajes permiten expresar esas diferencias en términos relativos.

Estas diferencias son descriptivas y no permiten determinar sus causas sin analizar otras variables, como el cargo o el grupo profesional.

In [ ]:
# PASO 4. EXTRA - TAMAÑO DE GRUPOS Y RATIOS SALARIALES

# Calcular número de personas y salario medio por género
tabla_ratios = df_transformado.groupby("Gènere")["Salari mensual"].agg(
    Personas="count",
    Media="mean"
)

# Calcular porcentaje de personas por género
tabla_ratios["Personas %"] = (
    tabla_ratios["Personas"] / tabla_ratios["Personas"].sum() * 100
)

# Calcular ratio salarial respecto a la media general
tabla_ratios["Ratio salarial"] = (
    tabla_ratios["Media"] / media_general
)

# Ordenar por salario medio
tabla_ratios = tabla_ratios.sort_values("Media", ascending=False)

# Mostrar resultados
display(
    tabla_ratios.style.format({
        "Media": "{:,.2f} €",
        "Personas %": "{:.2f} %",
        "Ratio salarial": "{:.2f}"
    }, thousands=".", decimal=",")
)

### Conclusión del ejercicio 4

Se han elaborado tablas descriptivas de salarios por género, calculando la media, mediana, mínimo y máximo, y ordenando los resultados por salario medio.

También se ha creado una tabla dinámica que compara los salarios medios por género y país de origen, incluyendo las medias en los márgenes y un formato condicional para identificar visualmente los valores más elevados.

En el análisis adicional se han calculado porcentajes y ratios salariales respecto a la media general de 1.570,14 €.

Los resultados muestran que el salario medio del grupo Home es un 8,38 % superior a la media general, el de Otros un 8,01 % superior y el de Dona un 5,37 % inferior.

Asimismo, se ha comprobado que los grupos tienen tamaños diferentes: Home representa el 38,79 % de los registros con género informado, Otros el 2,60 % y Dona el 58,61 %.

Los valores absolutos permiten conocer las diferencias salariales en euros, mientras que los porcentajes y ratios facilitan su comparación relativa. No obstante, estas medidas no eliminan las diferencias de composición entre grupos.

En conclusión, el análisis permite describir las diferencias observadas, sin atribuirlas directamente al género ni establecer relaciones causales.

Los porcentajes de personas se calculan sobre los 923 registros con género clasificado (358 + 24 + 541), no sobre los 985 registros totales, porque los valores nulos de género quedan excluidos de la agrupación.

# *Nivell 2 - Anàlisi amb dades enriquides i estructures múltiples*

---

# **Exercici 1: Enriquiment mitjançant datasets externs**
 - Anàlisi amb dades enriquides i estructures múltiples:Aspectes a revisar i analitzar**

---



» Les diferents fonts de dades són coherents i compatibles entre si per poder calcular un salari ajustat?
» La informació contextual incorporada (cost de vida, polítiques salarials) és suficient per aplicar increments de manera consistent?
» Hi ha buits d'informació que impedeixin calcular correctament l'increment salarial en alguns registres?
» És necessari prendre decisions analítiques quan la informació contextual és parcial o absent?
» Com poden aquestes decisions influir en el càlcul del salari ajustat i en la seva interpretació posterior?
Concretament, hauràs de:

» Integrar el dataset principal amb:
El dataset contextual de ciutats.
La política salarial definida en format JSON
» Calcular un increment salarial total combinant:
Grup professional.
Situació familiar.
Franja d'edat.
Cost de vida de la ciutat.
» Identificar quins registres no poden rebre algun dels ajustos i explicar-ne el motiu.
» Decidir, de manera raonada, com tractar aquests casos en el càlcul del salari ajustat, justificando l'impacte analític de la decisió presa.

In [ ]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 1
# PASO 1 - CARGAR ARCHIVOS EXTERNOS
# ==========================================================

import pandas as pd
import json

# 1. Cargar el archivo CSV de ciudades
df_ciudades = pd.read_csv(
    "sample_data/ciutats_context.csv",
    encoding="cp1252"
)

# 2. Cargar el archivo JSON de política salarial
with open("sample_data/politica_salarial.json", encoding="utf-8") as archivo:
    politica = json.load(archivo)

# 3. Mostrar dimensiones y primeras filas
print("DIMENSIONES DEL DATASET DE CIUDADES:")
print(df_ciudades.shape)

print("\nPRIMERAS CINCO FILAS:")
display(df_ciudades.head())

# 4. Mostrar política salarial
print("\nPOLÍTICA SALARIAL:")
print(politica)

DIMENSIONES DEL DATASET DE CIUDADES:
(36, 5)

PRIMERAS CINCO FILAS:

      Ciutat     País  Cost_vida_index  Transport_public_score  Clima_tipus
0  Barcelona  Espanya               78                     8.5  Mediterrani
1     Madrid  Espanya               75                     8.0  Continental
2   València  Espanya               70                     7.5  Mediterrani
3    Sevilla  Espanya               65                     7.0  Mediterrani
4     Bilbao  Espanya               72                     7.8      Oceànic

POLÍTICA SALARIAL:
{'base_increment_by_group': {'Grup A': 5.0, 'Grup B': 3.5, 'Grup C': 2.0, 'Grup D': 8.0}, 'children_adjustment': {'has_children': 1.5, 'no_children': 0.0}, 'age_adjustment': {'18-29': 0.0, '30-44': 1.0, '45-59': 2.0, '60+': 1.5}, 'cost_of_living_adjustment': {'low': 0.0, 'medium': 1.0, 'high': 2.0}, 'transport_adjustment': {'low': 0.5, 'medium': 0.0, 'high': -0.5}, 'rules': {'max_total_increment_percent': 15, 'min_salary_threshold': 800}}

In [ ]:
# VER EL CONTENIDO COMPLETO DEL CSV

display(df_ciudades)

,Ciutat,País,Cost_vida_index,Transport_public_score,Clima_tipus
0,Barcelona,Espanya,78,8.5,Mediterrani
1,Madrid,Espanya,75,8.0,Continental
2,València,Espanya,70,7.5,Mediterrani
3,Sevilla,Espanya,65,7.0,Mediterrani
4,Bilbao,Espanya,72,7.8,Oceànic
5,Zaragoza,Espanya,68,7.0,Continental
6,Murcia,Espanya,60,6.5,Mediterrani
7,Palma,Espanya,73,7.2,Mediterrani
8,Girona,Espanya,66,6.8,Mediterrani
9,Tarragona,Espanya,67,6.9,Mediterrani
10,A Coru\u00f1a,Espanya,69,7.1,Oceànic
11,Valladolid,Espanya,64,6.7,Continental
12,Alacant,Espanya,68,7.0,Mediterrani
13,Las Palmas de Gran Canaria,Espanya,62,6.8,Subtropical
14,Paris,França,85,9.0,Oceànic
15,Marseille,França,72,7.4,Mediterrani
16,Lyon,França,74,7.6,Continental
17,Bordeaux,França,73,7.2,Oceànic
18,Lille,França,71,7.3,Continental
19,Milano,Itàlia,80,7.5,Continental
20,Roma,Itàlia,78,7.6,Mediterrani
21,Torino,Itàlia,74,7.2,Continental
22,Genova,Itàlia,72,6.9,Mediterrani
23,Venezia,Itàlia,79,7.0,Mediterrani
24,Napoli,Itàlia,65,6.5,Mediterrani
25,Firenze,Itàlia,77,7.1,Continental
26,Berlin,Alemanya,76,8.5,Continental
27,Munchen,Alemanya,82,8.0,Continental
28,Hamburg,Alemanya,78,8.1,Oceànic
29,Frankfurt,Alemanya,80,8.3,Continental
30,Stuttgart,Alemanya,79,7.9,Continental
31,Leipzig,Alemanya,70,7.2,Continental
32,Oslo,Noruega,90,9.2,Fred
33,Bergen,Noruega,85,8.8,Oceànic
34,Paris,Estats Units,88,6.0,Continental
35,Valencia,Veneçuela,55,5.5,Tropical

In [ ]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 1
# PASO 2 - COMPROBAR COMPATIBILIDAD
# ==========================================================

# 1. Comprobar las columnas de ambos datasets
print("COLUMNAS DEL DATASET PRINCIPAL:")
print(df_transformado.columns.tolist())

print("\nCOLUMNAS DEL DATASET DE CIUDADES:")
print(df_ciudades.columns.tolist())

# 2. Buscar ciudades que no aparecen en el CSV
ciudades_sin_coincidencia = (
    set(df_transformado["Ciutat"].dropna())
    - set(df_ciudades["Ciutat"].dropna())
)

print("\nCIUDADES SIN COINCIDENCIA:")
print(ciudades_sin_coincidencia)

# 3. Buscar grupos profesionales que no aparecen en el JSON
grupos_sin_coincidencia = (
    set(df_transformado["Grup Professional"].dropna())
    - set(politica["base_increment_by_group"].keys())
)

print("\nGRUPOS PROFESIONALES SIN COINCIDENCIA:")
print(grupos_sin_coincidencia)

COLUMNAS DEL DATASET PRINCIPAL:
['Unnamed: 0', 'Nom', 'Cognoms', 'DNI', "País d'origen", 'Ciutat', 'Dia de Naixement', 'Mes de Naixement', 'Any de Naixement', 'Gènere', 'Salari mensual', 'Grup Professional', 'Càrrec', 'Nombre_fills', 'Te_cotxe', 'Km_anuals', 'Consum_mitja_L_100km', 'Temperatura_mitjana_ciutat']

COLUMNAS DEL DATASET DE CIUDADES:
['Ciutat', 'País', 'Cost_vida_index', 'Transport_public_score', 'Clima_tipus']

CIUDADES SIN COINCIDENCIA:
{'Nice', 'Stavanger', 'Bologna', 'A Coruña', 'Trondheim', 'Köln', 'Màlaga', 'Tromsø', 'Nantes', 'München', 'Düsseldorf', 'Toulouse'}

GRUPOS PROFESIONALES SIN COINCIDENCIA:
set()

Resultados
- Grupos profesionales: set() significa que todos los grupos del dataset principal están definidos en el JSON. Correcto.
- Ciudades: hay 12 nombres que no coinciden con el CSV externo: Nice, A Coruña, Stavanger, Tromsø, Málaga, Köln, Düsseldorf, München, Nantes, Toulouse, Trondheim y Bologna.
Esto no significa necesariamente que falten esas ciudades. Algunas pueden estar escritas de forma diferente en ambos archivos.
dentificado las 12 ciudades que no coinciden y sus países.
Esto es importante porque, si hacemos el merge() directamente, los empleados de esas ciudades podrían quedarse sin información sobre el coste de vida.

In [ ]:
# PASO 2.4 - NORMALIZAR NOMBRES DE CIUDADES /En el CSV aparece como A Coru\u00f1a (con los caracteres \u00f1 escritos literalmente).

df_enriquecido = df_transformado.copy()

# Corregir nombres para que coincidan con el CSV
df_enriquecido["Ciutat"] = df_enriquecido["Ciutat"].replace({
    "München": "Munchen",
    "A Coruña": r"A Coru\u00f1a"
})

# Comprobar las ciudades que siguen sin coincidencia
ciudades_pendientes = (
    set(df_enriquecido["Ciutat"].dropna())
    - set(df_ciudades["Ciutat"].dropna())
)

print("CIUDADES TODAVÍA SIN COINCIDENCIA:")
print(sorted(ciudades_pendientes))

CIUDADES TODAVÍA SIN COINCIDENCIA:
['Bologna', 'Düsseldorf', 'Köln', 'Màlaga', 'Nantes', 'Nice', 'Stavanger', 'Toulouse', 'Tromsø', 'Trondheim']

In [ ]:
# ==========================================================
# PASO 3 - UNIR DATASET PRINCIPAL Y CIUDADES
# ==========================================================

df_enriquecido = df_enriquecido.merge(
    df_ciudades,
    left_on=["Ciutat", "País d'origen"],
    right_on=["Ciutat", "País"],
    how="left",
    validate="many_to_one",
    indicator=True
)

# Comprobar dimensiones
print("DIMENSIONES DEL DATASET ENRIQUECIDO:")
print(df_enriquecido.shape)

# Comprobar coincidencias
print("\nRESULTADO DE LA UNIÓN:")
print(df_enriquecido["_merge"].value_counts())

# Mostrar primeras filas
display(df_enriquecido.head())

DIMENSIONES DEL DATASET ENRIQUECIDO:
(985, 23)

RESULTADO DE LA UNIÓN:
_merge
both          855
left_only     130
right_only      0
Name: count, dtype: int64

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,...,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat,País,Cost_vida_index,Transport_public_score,Clima_tipus,_merge
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,...,3.0,True,32108.0,25.0,10.1,Espanya,64.0,6.7,Continental,both
1,1,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,Home,...,0.0,True,19496.0,10.4,18.7,Espanya,68.0,7.0,Mediterrani,both
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,Dona,...,4.0,NaN,NaN,NaN,16.7,Espanya,68.0,7.0,Mediterrani,both
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,Home,...,2.0,False,NaN,NaN,18.3,Espanya,65.0,7.0,Mediterrani,both
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,...,0.0,True,NaN,11.8,13.1,Espanya,72.0,7.8,Oceànic,both

In [ ]:
# ==========================================================
# PASO 4 - IDENTIFICAR REGISTROS SIN DATOS DE CIUDAD
# ==========================================================

# 1. Seleccionar empleados sin coincidencia
sin_contexto = df_enriquecido[
    df_enriquecido["_merge"] == "left_only"
]

# 2. Contar empleados afectados
print("EMPLEADOS SIN INFORMACIÓN CONTEXTUAL:")
print(len(sin_contexto))

# 3. Contar empleados afectados por ciudad
print("\nEMPLEADOS AFECTADOS POR CIUDAD:")

display(
    sin_contexto["Ciutat"].value_counts()
)

EMPLEADOS SIN INFORMACIÓN CONTEXTUAL:
130

EMPLEADOS AFECTADOS POR CIUDAD:

Ciutat
Màlaga        53
Toulouse      15
Nantes        12
Bologna       11
Nice          11
Stavanger      9
Trondheim      6
Düsseldorf     5
Tromsø         4
Köln           4
Name: count, dtype: int64

In [ ]:
# ==========================================================
# PASO 4.2 - COMPROBAR DATOS NECESARIOS
# ==========================================================

# 1. Comprobar valores vacíos
columnas = [
    "Grup Professional",
    "Nombre_fills",
    "Any de Naixement",
    "Cost_vida_index"
]

print("VALORES VACÍOS POR COLUMNA:")
print(df_enriquecido[columnas].isna().sum())

# 2. Comprobar los grupos profesionales
print("\nGRUPOS PROFESIONALES:")
print(df_enriquecido["Grup Professional"].value_counts(dropna=False))

# 3. Comprobar el número de hijos
print("\nNÚMERO DE HIJOS:")
print(df_enriquecido["Nombre_fills"].value_counts(dropna=False))

VALORES VACÍOS POR COLUMNA:
Grup Professional      0
Nombre_fills          32
Any de Naixement       0
Cost_vida_index      130
dtype: int64

GRUPOS PROFESIONALES:
Grup Professional
Grup A    456
Grup B    350
Grup C    139
Grup D     40
Name: count, dtype: int64

NÚMERO DE HIJOS:
Nombre_fills
0.0    563
1.0    170
2.0     79
4.0     77
3.0     64
NaN     32
Name: count, dtype: int64

In [ ]:
# ==========================================================
# PASO 4.3 - COMPROBAR FECHAS DE NACIMIENTO
# ==========================================================

columnas_fecha = [
    "Dia de Naixement",
    "Mes de Naixement",
    "Any de Naixement"
]

# 1. Comprobar valores vacíos
print("VALORES VACÍOS EN LAS FECHAS:")
print(df_enriquecido[columnas_fecha].isna().sum())

# 2. Comprobar los años de nacimiento
print("\nAÑOS DE NACIMIENTO:")
print(df_enriquecido["Any de Naixement"].describe())

# 3. Comprobar las fechas completas
fechas = pd.to_datetime(
    df_enriquecido["Any de Naixement"].astype("Int64").astype(str) + "-" +
    df_enriquecido["Mes de Naixement"].astype("Int64").astype(str) + "-" +
    df_enriquecido["Dia de Naixement"].astype("Int64").astype(str),
    errors="coerce"
)

print("\nFECHAS INVÁLIDAS O INCOMPLETAS:")
print(fechas.isna().sum())

VALORES VACÍOS EN LAS FECHAS:
Dia de Naixement    0
Mes de Naixement    0
Any de Naixement    0
dtype: int64

AÑOS DE NACIMIENTO:
count     985.000000
mean     2001.737056
std       141.033327
min      1940.000000
25%      1969.000000
50%      1982.000000
75%      1995.000000
max      3000.000000
Name: Any de Naixement, dtype: float64

FECHAS INVÁLIDAS O INCOMPLETAS:
77

aunque las columnas de nacimiento no tienen valores vacíos, existen fechas incorrectas que impiden calcular la edad de algunos empleados.. Utilizaremos las fechas válidas para calcular la edad y dejaremos el ajuste por edad como no calculable cuando la fecha sea incorrecta.
Así cumplimos el enunciado: identificar la información insuficiente, justificar nuestra decisión y explicar su impacto en el salario ajustado.

In [ ]:
# ==========================================================
# PASO 5 - CALCULAR EDADES Y FRANJAS DE EDAD / podemos calcular el ajuste por edad para 908 empleados. Los otros 77 conservarán el ajuste como desconocido.
# ==========================================================

# 1. Guardar las fechas de nacimiento
df_enriquecido["Fecha_nacimiento"] = fechas

# 2. Calcular la edad a fecha 18/10/2026
fecha_referencia = pd.Timestamp("2026-10-18")

df_enriquecido["Edad"] = (
    fecha_referencia.year
    - df_enriquecido["Fecha_nacimiento"].dt.year
    - (
        fecha_referencia.strftime("%m%d")
        < df_enriquecido["Fecha_nacimiento"].dt.strftime("%m%d")
    )
)

# 3. Descartar edades imposibles o inferiores a 18 años
df_enriquecido.loc[
    (df_enriquecido["Edad"] < 18) |
    (df_enriquecido["Edad"] > 100),
    "Edad"
] = float("nan")

# 4. Asignar franjas de edad
def clasificar_edad(edad):

    if pd.isna(edad):
        return None
    elif edad < 30:
        return "18-29"
    elif edad < 45:
        return "30-44"
    elif edad < 60:
        return "45-59"
    else:
        return "60+"

df_enriquecido["Franja_edad"] = (
    df_enriquecido["Edad"].apply(clasificar_edad)
)

# 5. Mostrar resultados
print("EMPLEADOS POR FRANJA DE EDAD:")
print(df_enriquecido["Franja_edad"].value_counts(dropna=False))

display(
    df_enriquecido[
        ["Nom", "Fecha_nacimiento", "Edad", "Franja_edad"]
    ].head(10)
)

EMPLEADOS POR FRANJA DE EDAD:
Franja_edad
30-44    299
45-59    280
60+      174
18-29    155
None      77
Name: count, dtype: int64

      Nom Fecha_nacimiento  Edad Franja_edad
0   Joana       1958-03-23  68.0         60+
1    Marc       1960-11-08  65.0         60+
2     Noa       1961-04-27  65.0         60+
3     Pol       1985-10-13  41.0       30-44
4   David       1965-11-29  60.0         60+
5  Alexia       1978-08-01  48.0       45-59
6   David       1971-09-25  55.0       45-59
7  Carmen       1962-09-08  64.0         60+
8    Nora       1963-03-08  63.0         60+
9    Alba              NaT   NaN        None

In [ ]:
# ==========================================================
# PASO 6 - APLICAR INCREMENTOS SALARIALES
# ==========================================================

# 1. Incremento por grupo profesional
df_enriquecido["Incremento_grupo"] = (
    df_enriquecido["Grup Professional"].map(
        politica["base_increment_by_group"]
    )
)

# 2. Incremento por hijos
def incremento_hijos(numero_hijos):

    if pd.isna(numero_hijos):
        return None
    elif numero_hijos > 0:
        return politica["children_adjustment"]["has_children"]
    else:
        return politica["children_adjustment"]["no_children"]

df_enriquecido["Incremento_hijos"] = (
    df_enriquecido["Nombre_fills"].apply(incremento_hijos)
)

# 3. Incremento por edad
df_enriquecido["Incremento_edad"] = (
    df_enriquecido["Franja_edad"].map(
        politica["age_adjustment"]
    )
)

# 4. Comprobar resultados
print("VALORES VACÍOS EN LOS INCREMENTOS:")
print(
    df_enriquecido[
        ["Incremento_grupo", "Incremento_hijos", "Incremento_edad"]
    ].isna().sum()
)

display(
    df_enriquecido[
        ["Nom", "Grup Professional", "Incremento_grupo",
         "Nombre_fills", "Incremento_hijos",
         "Franja_edad", "Incremento_edad"]
    ].head(10)
)

VALORES VACÍOS EN LOS INCREMENTOS:
Incremento_grupo     0
Incremento_hijos    32
Incremento_edad     77
dtype: int64

,Nom,Grup Professional,Incremento_grupo,Nombre_fills,Incremento_hijos,Franja_edad,Incremento_edad
0,Joana,Grup B,3.5,3.0,1.5,60+,1.5
1,Marc,Grup C,2.0,0.0,0.0,60+,1.5
2,Noa,Grup A,5.0,4.0,1.5,60+,1.5
3,Pol,Grup B,3.5,2.0,1.5,30-44,1.0
4,David,Grup B,3.5,0.0,0.0,60+,1.5
5,Alexia,Grup B,3.5,0.0,0.0,45-59,2.0
6,David,Grup B,3.5,0.0,0.0,45-59,2.0
7,Carmen,Grup C,2.0,4.0,1.5,60+,1.5
8,Nora,Grup B,3.5,0.0,0.0,60+,1.5
9,Alba,Grup A,5.0,4.0,1.5,None,NaN

Pero nuestro CSV contiene Cost_vida_index, un índice numérico, no las categorías low, medium y high.
Por tanto, antes de aplicar los porcentajes necesitamos saber cómo convertir ese índice en categorías. El JSON no especifica los límites, así que tendremos que definirlos y justificar nuestra decisión.

In [ ]:
# ==========================================================
# PASO 7.1 - ANALIZAR EL ÍNDICE DE COSTE DE VIDA
# ==========================================================

# 1. Estadísticas del índice
print("ESTADÍSTICAS DEL COSTE DE VIDA:")
print(df_ciudades["Cost_vida_index"].describe())

# 2. Mostrar ciudades e índices
print("\nCOSTE DE VIDA POR CIUDAD:")

display(
    df_ciudades[
        ["Ciutat", "País", "Cost_vida_index"]
    ].sort_values("Cost_vida_index")
)

ESTADÍSTICAS DEL COSTE DE VIDA:
count    36.000000
mean     73.333333
std       7.844926
min      55.000000
25%      68.000000
50%      73.000000
75%      78.250000
max      90.000000
Name: Cost_vida_index, dtype: float64

COSTE DE VIDA POR CIUDAD:

                        Ciutat          País  Cost_vida_index
35                    Valencia     Veneçuela               55
6                       Murcia       Espanya               60
13  Las Palmas de Gran Canaria       Espanya               62
11                  Valladolid       Espanya               64
24                      Napoli        Itàlia               65
3                      Sevilla       Espanya               65
8                       Girona       Espanya               66
9                    Tarragona       Espanya               67
12                     Alacant       Espanya               68
5                     Zaragoza       Espanya               68
10               A Coru\u00f1a       Espanya               69
31                     Leipzig      Alemanya               70
2                     València       Espanya               70
18                       Lille        França               71
15                   Marseille        França               72
22                      Genova        Itàlia               72
4                       Bilbao       Espanya               72
17                    Bordeaux        França               73
7                        Palma       Espanya               73
21                      Torino        Itàlia               74
16                        Lyon        França               74
1                       Madrid       Espanya               75
26                      Berlin      Alemanya               76
25                     Firenze        Itàlia               77
20                        Roma        Itàlia               78
28                     Hamburg      Alemanya               78
0                    Barcelona       Espanya               78
30                   Stuttgart      Alemanya               79
23                     Venezia        Itàlia               79
29                   Frankfurt      Alemanya               80
19                      Milano        Itàlia               80
27                     Munchen      Alemanya               82
14                       Paris        França               85
33                      Bergen       Noruega               85
34                       Paris  Estats Units               88
32                        Oslo       Noruega               90

In [ ]:
# PASO 7.2 - CLASIFICAR EL COSTE DE VIDA

def clasificar_coste(indice):

    if pd.isna(indice):
        return None
    elif indice < 68:
        return "low"
    elif indice <= 78:
        return "medium"
    else:
        return "high"

# Crear categoría de coste de vida
df_enriquecido["Categoria_coste"] = (
    df_enriquecido["Cost_vida_index"].apply(clasificar_coste)
)

# Aplicar incrementos del JSON
df_enriquecido["Incremento_coste"] = (
    df_enriquecido["Categoria_coste"].map(
        politica["cost_of_living_adjustment"]
    )
)

# Comprobar resultados
print("EMPLEADOS POR CATEGORÍA:")
print(df_enriquecido["Categoria_coste"].value_counts(dropna=False))

print("\nINCREMENTOS SIN CALCULAR:")
print(df_enriquecido["Incremento_coste"].isna().sum())

EMPLEADOS POR CATEGORÍA:
Categoria_coste
medium    492
low       294
None      130
high       69
Name: count, dtype: int64

INCREMENTOS SIN CALCULAR:
130

In [ ]:
# ==========================================================
# PASO 8 - CALCULAR EL SALARIO AJUSTADO
# ==========================================================

# 1. Seleccionar los cuatro incrementos
columnas_incrementos = [
    "Incremento_grupo",
    "Incremento_hijos",
    "Incremento_edad",
    "Incremento_coste"
]

# 2. Calcular el incremento total
df_enriquecido["Incremento_total"] = (
    df_enriquecido[columnas_incrementos].sum(
        axis=1, min_count=4
    )
)

# 3. Aplicar el límite máximo del 15 %
limite = politica["rules"]["max_total_increment_percent"]

df_enriquecido["Incremento_total"] = (
    df_enriquecido["Incremento_total"].clip(upper=limite)
)

# 4. Calcular el salario ajustado
df_enriquecido["Salario_ajustado"] = (
    df_enriquecido["Salari mensual"] *
    (1 + df_enriquecido["Incremento_total"] / 100)
)

# 5. Mostrar resultados
print("SALARIOS CALCULADOS:")
print(df_enriquecido["Salario_ajustado"].notna().sum())

print("\nSALARIOS PENDIENTES:")
print(df_enriquecido["Salario_ajustado"].isna().sum())

display(
    df_enriquecido[
        ["Nom", "Salari mensual",
         "Incremento_total", "Salario_ajustado"]
    ].head(10).style.format({
        "Salari mensual": "{:,.2f} €",
        "Incremento_total": "{:.2f} %",
        "Salario_ajustado": "{:,.2f} €"
    }, na_rep="—")
)

SALARIOS CALCULADOS:
759

SALARIOS PENDIENTES:
226

Se ha enriquecido el dataset principal de 985 empleados mediante la integración del archivo CSV de ciudades europeas y la política salarial definida en formato JSON.

Durante el proceso se han detectado diferencias en los nombres de algunas ciudades, que se han corregido para facilitar la integración. Después de la unión, 130 empleados no disponen de información contextual sobre el coste de vida.

También se han identificado 32 empleados sin información sobre el número de hijos y 77 registros con fechas de nacimiento inválidas o insuficientes para determinar correctamente la edad.

Para calcular los incrementos salariales se han considerado cuatro factores: grupo profesional, situación familiar, franja de edad y coste de vida de la ciudad. Se ha contemplado el límite máximo de incremento del 15 % establecido en la política salarial.

**Resultados del cálculo salarial:**

- 759 empleados con salario ajustado calculado.
- 226 empleados pendientes por información insuficiente.


Se ha decidido mantener como desconocidos los ajustes que no pueden calcularse por falta de información, en lugar de asignar valores inventados. Esta decisión reduce el número de salarios ajustados disponibles, pero evita presentar cálculos parciales como si fueran definitivos.

Para clasificar el coste de vida se han utilizado tres categorías: bajo, medio y alto, mediante los límites numéricos de 68 y 78 establecidos en el código. Estos límites constituyen una decisión analítica que debe justificarse, ya que no están definidos expresamente en la política salarial JSON.

En conclusión, el ejercicio demuestra que la integración de fuentes externas permite enriquecer el análisis salarial, pero también introduce incertidumbre cuando existen datos incompletos. Las decisiones adoptadas sobre estos registros condicionan tanto el número de salarios calculados como su interpretación posterior.

# Exercici 2: Reestructuració del dataset Aspectes a revisar i analitzar

» Existeixen variables que representen conceptes similars o relacionats, però estan distribuïdes en diferents columnes?
»El format actual del dataset facilita o dificulta:
comparacions entre magnituds.
agregacions per grups.
» Quin impacte té la forma del dataset (ample vs llarg) en la lectura i interpretació de les dades?
Concretament, hauràs de:

» Reestructurar el dataset utilitzant melt() per convertir-lo a format llarg, definint prèviament:
les columnes que actuen com a identificadores (per exemple: persona, ciutat, grup professional, gènere, etc.).
les columnes que passen a representar valors mesurats (per exemple: salaris, mobilitat, variables contextuals).
» Analitzar per què el format llarg és més adequat per:
realitzar comparacions entre diferents tipus de variables.
calcular estadístics agregats.

In [ ]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 2
# PASO 1 - SELECCIONAR COLUMNAS
# ==========================================================

# Columnas identificadoras
identificadores = [
    "DNI",
    "Nom",
    "Ciutat",
    "Grup Professional",
    "Gènere"
]

# Variables que transformaremos a formato largo
variables = [
    "Salari mensual",
    "Salario_ajustado",
    "Km_anuals",
    "Consum_mitja_L_100km",
    "Temperatura_mitjana_ciutat"
]

# Comprobar que las columnas existen
print("COLUMNAS IDENTIFICADORAS:")
print(identificadores)

print("\nVARIABLES MEDIDAS:")
print(variables)

# Mostrar una muestra del dataset
display(
    df_enriquecido[identificadores + variables].head()
)

COLUMNAS IDENTIFICADORAS:
['DNI', 'Nom', 'Ciutat', 'Grup Professional', 'Gènere']

VARIABLES MEDIDAS:
['Salari mensual', 'Salario_ajustado', 'Km_anuals', 'Consum_mitja_L_100km', 'Temperatura_mitjana_ciutat']

,DNI,Nom,Ciutat,Grup Professional,Gènere,Salari mensual,Salario_ajustado,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,66722344X,Joana,Valladolid,Grup B,Dona,1469.0,1564.485,32108.0,25.0,10.1
1,48840994W,Marc,Alacant,Grup C,Home,2718.0,2840.310,19496.0,10.4,18.7
2,14308421X,Noa,Alacant,Grup A,Dona,1358.0,1480.220,NaN,NaN,16.7
3,58586340F,Pol,Sevilla,Grup B,Home,1478.0,1566.680,NaN,NaN,18.3
4,82070937P,David,Bilbao,Grup B,Dona,1284.0,1361.040,NaN,11.8,13.1

In [ ]:

# PASO 2 - TRANSFORMAR A FORMATO LARGO
# ==========================================================

df_largo = df_enriquecido.melt(
    id_vars=identificadores,
    value_vars=variables,
    var_name="Variable",
    value_name="Valor"
)

# Comprobar dimensiones
print("DIMENSIONES DEL DATASET ORIGINAL:")
print(df_enriquecido.shape)

print("\nDIMENSIONES DEL DATASET LARGO:")
print(df_largo.shape)

# Mostrar las primeras filas
display(df_largo.head(10))

DIMENSIONES DEL DATASET ORIGINAL:
(985, 33)

DIMENSIONES DEL DATASET LARGO:
(4925, 7)

,DNI,Nom,Ciutat,Grup Professional,Gènere,Variable,Valor
0,66722344X,Joana,Valladolid,Grup B,Dona,Salari mensual,1469.0
1,48840994W,Marc,Alacant,Grup C,Home,Salari mensual,2718.0
2,14308421X,Noa,Alacant,Grup A,Dona,Salari mensual,1358.0
3,58586340F,Pol,Sevilla,Grup B,Home,Salari mensual,1478.0
4,82070937P,David,Bilbao,Grup B,Dona,Salari mensual,1284.0
5,25014631B,Alexia,Las Palmas de Gran Canaria,Grup B,Dona,Salari mensual,2069.0
6,36998038E,David,Palma,Grup B,Dona,Salari mensual,2349.0
7,47376585K,Carmen,Barcelona,Grup C,Home,Salari mensual,2855.0
8,37289414J,Nora,Stavanger,Grup B,Dona,Salari mensual,1338.0
9,75181648S,Alba,Las Palmas de Gran Canaria,Grup A,Home,Salari mensual,1450.0

In [ ]:

# PASO 3 - COMPROBAR VALORES NULOS
# ==========================================================

# Contar valores nulos por variable
nulos = df_largo.groupby("Variable")["Valor"].apply(
    lambda x: x.isna().sum()
)

print("VALORES NULOS POR VARIABLE:")
print(nulos)

# Comprobar número de registros por variable
print("\nREGISTROS POR VARIABLE:")
print(df_largo["Variable"].value_counts())

VALORES NULOS POR VARIABLE:
Variable
Consum_mitja_L_100km          728
Km_anuals                     675
Salari mensual                  0
Salario_ajustado              226
Temperatura_mitjana_ciutat      0
Name: Valor, dtype: int64

REGISTROS POR VARIABLE:
Variable
Salari mensual                985
Salario_ajustado              985
Km_anuals                     985
Consum_mitja_L_100km          985
Temperatura_mitjana_ciutat    985
Name: count, dtype: int64

In [ ]:

# PASO 4 - ESTADÍSTICAS AGRUPADAS
# ==========================================================

# Calcular la media de cada variable por grupo profesional
estadisticas = df_largo.groupby(
    ["Grup Professional", "Variable"]
)["Valor"].mean().round(2)

print("MEDIA POR GRUPO PROFESIONAL Y VARIABLE:")
display(estadisticas.reset_index())

MEDIA POR GRUPO PROFESIONAL Y VARIABLE:

   Grup Professional                    Variable     Valor
0             Grup A        Consum_mitja_L_100km     11.30
1             Grup A                   Km_anuals  60063.10
2             Grup A              Salari mensual   1110.12
3             Grup A            Salario_ajustado   1182.30
4             Grup A  Temperatura_mitjana_ciutat     15.38
5             Grup B        Consum_mitja_L_100km     10.64
6             Grup B                   Km_anuals  53676.70
7             Grup B              Salari mensual   1650.60
8             Grup B            Salario_ajustado   1747.87
9             Grup B  Temperatura_mitjana_ciutat     15.36
10            Grup C        Consum_mitja_L_100km     10.43
11            Grup C                   Km_anuals  51543.38
12            Grup C              Salari mensual   2382.92
13            Grup C            Salario_ajustado   2482.15
14            Grup C  Temperatura_mitjana_ciutat     15.46
15            Grup D        Consum_mitja_L_100km     14.05
16            Grup D                   Km_anuals  45968.31
17            Grup D              Salari mensual   3166.62
18            Grup D            Salario_ajustado   3502.16
19            Grup D  Temperatura_mitjana_ciutat     15.39

In [ ]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 2
# CONCLUSIONES FINALES
# ==========================================================

print("CONCLUSIONES DEL EJERCICIO 2")
print("=" * 50)

print("1. El dataset original tenía 985 filas y 33 columnas.")

print("2. Con melt() hemos obtenido 4925 filas y 7 columnas.")

print("3. El formato ancho facilita consultar todos los datos de un empleado.")

print("4. El formato largo facilita agrupar y comparar una misma variable.")

print("5. Con groupby() podemos calcular medias por grupo profesional.")

print("6. Los valores nulos se han conservado sin sustituirlos por cero.")

print("7. No debemos mezclar variables con unidades diferentes.")

CONCLUSIONES DEL EJERCICIO 2
==================================================
1. El dataset original tenía 985 filas y 33 columnas.
2. Con melt() hemos obtenido 4925 filas y 7 columnas.
3. El formato ancho facilita consultar todos los datos de un empleado.
4. El formato largo facilita agrupar y comparar una misma variable.
5. Con groupby() podemos calcular medias por grupo profesional.
6. Los valores nulos se han conservado sin sustituirlos por cero.
7. No debemos mezclar variables con unidades diferentes.

#Comentario Ejercico  2 Nivel  2
En este ejercicio hemos utilizado la función melt() de Pandas para transformar el dataset de formato ancho a formato largo, pasando de 985 filas y 33 columnas a 4.925 filas y 7 columnas.

Esta transformación permite organizar los salarios, los datos de movilidad y las variables climáticas en una estructura más adecuada para realizar comparaciones y calcular estadísticas por grupo profesional mediante groupby().

También hemos comprobado que se conservan los valores nulos, sin sustituirlos por cero ni eliminar registros durante la transformación.

El formato largo facilita las comparaciones de una misma variable entre diferentes grupos. Sin embargo, debemos tener en cuenta que las variables tienen unidades distintas, como euros, kilómetros y grados, por lo que no deben compararse directamente entre sí.

Finalmente, el dataset queda preparado para realizar análisis comparativos y visualizaciones en ejercicios posteriores, sin necesidad de generar gráficos en este ejercicio.

## **Exercici 3: Creació de variables derivades (Feature Engineering)**

---


» Índex de dependència familiar: Salari mensual / (Nombre fills + 1).
» Índex de mobilitat: Km anuals / Temperatura mitjana.
» Ràtio salari / cost de vida.
» Indicador de dependència familiar: Salari / Nombre fills.
» Pes de responsabilitat familiar: Nombre fills * Edat.
» Indicador de etapa vital: 0 → sense càrregues, 1 → etapa activa, 2 → alta dependència.
Concretament, hauràs de:

» Crear almenys 3 variables derivades.
» Justificar:
La seva utilitat analítica.
Les decisions preses.
» Detectar casos límit o incoherents generats per les noves variables.
📌 Nota

El feature engineering es realitza sobre el dataset en format ample, ja que la creació de variables derivades requereix combinar informació de naturalesa diferent. El format llarg s'utilitza posteriorment per facilitar comparacions, agregacions i anàlisis descriptives de les variables generades.

In [ ]:

# PASO 1 - COMPROBAR COLUMNAS
# ==========================================================

print("COLUMNAS DISPONIBLES:")
print(df_enriquecido.columns.tolist())

# Comprobar los datos que utilizaremos
columnas = [
    "Salari mensual",
    "Nombre_fills",
    "Cost_vida_index",
    "Edad"
]

for columna in columnas:
    print(columna, ":", columna in df_enriquecido.columns)

COLUMNAS DISPONIBLES:
['Unnamed: 0', 'Nom', 'Cognoms', 'DNI', "País d'origen", 'Ciutat', 'Dia de Naixement', 'Mes de Naixement', 'Any de Naixement', 'Gènere', 'Salari mensual', 'Grup Professional', 'Càrrec', 'Nombre_fills', 'Te_cotxe', 'Km_anuals', 'Consum_mitja_L_100km', 'Temperatura_mitjana_ciutat', 'País', 'Cost_vida_index', 'Transport_public_score', 'Clima_tipus', '_merge', 'Fecha_nacimiento', 'Edad', 'Franja_edad', 'Incremento_grupo', 'Incremento_hijos', 'Incremento_edad', 'Categoria_coste', 'Incremento_coste', 'Incremento_total', 'Salario_ajustado']
Salari mensual : True
Nombre_fills : True
Cost_vida_index : True
Edad : True

In [ ]:

# PASO 2 - ÍNDICE DE DEPENDENCIA FAMILIAR
# ==========================================================

# Crear una copia del dataset original
df_derivadas = df_enriquecido.copy()

# Crear el índice de dependencia familiar
# Sumamos 1 para evitar dividir entre cero cuando no tiene hijos
df_derivadas["Indice_dependencia_familiar"] = (
    df_derivadas["Salari mensual"] /
    (df_derivadas["Nombre_fills"] + 1)
)

# Mostrar resultados con formato de euros/FALTA INDICE MOVILIDAD
display(
    df_derivadas[
        ["Nom", "Salari mensual", "Nombre_fills",
         "Indice_dependencia_familiar"]
    ].head(10).style.format({
        "Salari mensual": "{:,.0f} €",
        "Nombre_fills": "{:.0f}",
        "Indice_dependencia_familiar": "{:,.2f} €"
    }, na_rep="—")
)

# Comprobar casos límite del índice familiar

print("Número de hijos nulo:",
      df_derivadas["Nombre_fills"].isna().sum())

print("Número de hijos negativo:",
      (df_derivadas["Nombre_fills"] < 0).sum())

print("Índices familiares nulos:",
      df_derivadas["Indice_dependencia_familiar"].isna().sum())

Número de hijos nulo: 32
Número de hijos negativo: 0
Índices familiares nulos: 32

Los 32 índices nulos corresponden a empleados cuyo número de hijos es desconocido. No debemos sustituir esos valores por cero, porque estaríamos suponiendo que no tienen hijos.

Además, no existen valores negativos en Nombre_fills, por lo que no hemos detectado esa incoherencia.

Se ha creado el índice de dependencia familiar dividiendo el salario mensual entre el número de hijos más uno. Se añade uno al denominador para evitar divisiones por cero cuando el empleado no tiene hijos.

Se han detectado 32 registros sin información sobre el número de hijos, que generan 32 índices nulos. Estos valores se mantienen como nulos para evitar realizar suposiciones sobre la situación familiar de los empleados.

No se han encontrado números negativos de hijos.

Este indicador permite explorar la relación entre salario y número de hijos, aunque no representa directamente la capacidad económica real de una familia.

In [ ]:

# PASO 3 - RATIO SALARIO / COSTE DE VIDA
# Comparar salarios según el coste de vida de cada ciudad
# ==========================================================

# Crear la segunda variable derivada
df_derivadas["Ratio_salario_coste_vida"] = (
    df_derivadas["Salari mensual"] /
    df_derivadas["Cost_vida_index"].replace(0, float("nan"))
)

# Mostrar resultados con formato
display(
    df_derivadas[
        ["Nom", "Ciutat", "Salari mensual",
         "Cost_vida_index", "Ratio_salario_coste_vida"]
    ].head(10).style.format({
        "Salari mensual": "{:,.0f} €",
        "Cost_vida_index": "{:.0f}",
        "Ratio_salario_coste_vida": "{:.2f}"
    }, na_rep="—")
)


# Comprobar casos límite del ratio salario / coste de vida

print("Costes de vida nulos:",
      df_derivadas["Cost_vida_index"].isna().sum())

print("Costes de vida iguales a cero:",
      (df_derivadas["Cost_vida_index"] == 0).sum())

print("Costes de vida negativos:",
      (df_derivadas["Cost_vida_index"] < 0).sum())

print("Ratios salariales nulos:",
      df_derivadas["Ratio_salario_coste_vida"].isna().sum())

Costes de vida nulos: 130
Costes de vida iguales a cero: 0
Costes de vida negativos: 0
Ratios salariales nulos: 130

La fórmula es:
\[
\text{Ratio salario/coste de vida}=\frac{\text{Salario mensual}}{\text{Índice de coste de vida}}
\]
utilizado  .replace(0, float("nan")) para evitar divisiones por cero.

 Joana tiene un ratio de 22,95 y Carmen de 36,60. Estos valores son indicadores relativos, no importes en euros ni medidas directas del poder adquisitivo.

In [ ]:

# PASO 5 - PESO DE RESPONSABILIDAD FAMILIAR
# ==================================================

# 1. Crear la tercera variable derivada
# Multiplicamos el número de hijos por la edad

df_derivadas["Peso_responsabilidad_familiar"] = (
    df_derivadas["Nombre_fills"] * df_derivadas["Edad"]
)

# 2. Mostrar los primeros 10 resultados
display(
    df_derivadas[
        ["Nom", "Nombre_fills", "Edad",
         "Peso_responsabilidad_familiar"]
    ].head(10).style.format({
        "Nombre_fills": "{:.0f}",
        "Edad": "{:.0f}",
        "Peso_responsabilidad_familiar": "{:.0f}"
    }, na_rep="-")
)

# 3. Comprobar casos límite

# Contar edades nulas
print("Edades nulas:",
      df_derivadas["Edad"].isna().sum())

# Detectar edades fuera del rango de revisión
print("Edades fuera del rango 18-100:",
      ((df_derivadas["Edad"] < 18) |
       (df_derivadas["Edad"] > 100)).sum())

# Contar registros sin información sobre hijos
print("Número de hijos nulo:",
      df_derivadas["Nombre_fills"].isna().sum())

# Contar pesos familiares nulos
print("Pesos familiares nulos:",
      df_derivadas["Peso_responsabilidad_familiar"].isna().sum())

# Detectar pesos familiares negativos
print("Pesos familiares negativos:",
      (df_derivadas["Peso_responsabilidad_familiar"] < 0).sum())

Edades nulas: 77
Edades fuera del rango 18-100: 0
Número de hijos nulo: 32
Pesos familiares nulos: 108
Pesos familiares negativos: 0

Se ha creado la tercera variable derivada, Peso_responsabilidad_familiar, multiplicando el número de hijos por la edad del empleado.

Este indicador combina dos características personales para facilitar comparaciones entre empleados, aunque no representa directamente la responsabilidad económica familiar.

Se han detectado 77 edades nulas y 32 registros sin información sobre el número de hijos. Como consecuencia, 108 empleados presentan un peso de responsabilidad familiar nulo.

No se han encontrado edades fuera del intervalo de revisión de 18 a 100 años.

Los valores desconocidos se mantienen como nulos para evitar generar resultados basados en información incompleta.

# **Exercici 4: Exportació i síntesi de resultats**

---


🎯 Objectiu: consolidar els resultats obtinguts després de la preparació, enriquiment i creació de variables, i generar sortides estructurades reutilitzables per a anàlisi o reporting.
En aquest exercici es vol posar el focus en:

» L'organització de les dades per grups rellevants.
» La generació de datasets finals coherents.
» La capacitat de sintetitzar informació clau.
Aspectes a revisar i analitzar:

» Quin nivell d'agrupació és més adequat per a l'exportació de resultats?
» Com separar dades detallades de dades agregades?
» Quina informació és rellevant per a un ús posterior (anàlisi, visualització, reporting)?
Concretament, hauràs de:

» Utilitzant un bucle, exportar en 4 fitxers (format .csv o .xlsx) les dades corresponents a cada Grup Professional. Per exemple: dades_GrupA.csv, dades_GrupB.csv...
» Crear i exportar un cinquè DataFrame (format .csv o .xlsx) que contingui, per a cada Grup Professional:
Nombre total de treballadors.
Salari mitjà.
Edat mediana.

In [ ]:

# PASO 1 - COMPROBAR GRUPOS PROFESIONALES
# ==================================================

# Mostrar los grupos profesionales disponibles
print("GRUPOS PROFESIONALES:")
print(df_derivadas["Grup Professional"].value_counts())

# Comprobar las dimensiones del dataset
print("\nDIMENSIONES DEL DATASET:")
print(df_derivadas.shape)

# Comprobar las columnas necesarias
print("\nCOLUMNAS NECESARIAS:")

columnas = ["Grup Professional", "Salari mensual", "Edad"]

for columna in columnas:
    print(columna, ":", columna in df_derivadas.columns)

GRUPOS PROFESIONALES:
Grup Professional
Grup A    456
Grup B    350
Grup C    139
Grup D     40
Name: count, dtype: int64

DIMENSIONES DEL DATASET:
(985, 36)

COLUMNAS NECESARIAS:
Grup Professional : True
Salari mensual : True
Edad : True

In [ ]:
# ==================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 4
# PASO 2 - EXPORTAR LOS GRUPOS PROFESIONALES
# ==================================================

# Crear una lista con los cuatro grupos
grupos = ["Grup A", "Grup B", "Grup C", "Grup D"]

# Recorrer cada grupo mediante un bucle
for grupo in grupos:

    # Seleccionar los trabajadores del grupo
    df_grupo = df_derivadas[
        df_derivadas["Grup Professional"] == grupo
    ]

    # Crear el nombre del archivo
    nombre_archivo = "datos_" + grupo.replace(" ", "") + ".csv"

    # Exportar los datos a CSV
    df_grupo.to_csv(
        nombre_archivo,
        index=False,
        encoding="utf-8-sig",
        sep=";"
    )

    # Comprobar la exportación
    print(nombre_archivo, "- Trabajadores:", len(df_grupo))

datos_GrupA.csv - Trabajadores: 456
datos_GrupB.csv - Trabajadores: 350
datos_GrupC.csv - Trabajadores: 139
datos_GrupD.csv - Trabajadores: 40

In [ ]:
# ==================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 4
# PASO 3 - CREAR TABLA RESUMEN
# ==================================================

# Agrupar por grupo profesional y calcular estadísticas
df_resumen = (
    df_derivadas.groupby("Grup Professional")
    .agg(
        Trabajadores=("DNI", "count"),
        Salario_medio=("Salari mensual", "mean"),
        Edad_mediana=("Edad", "median")
    )
    .reset_index()
)

# Mostrar la tabla resumen
print("RESUMEN POR GRUPO PROFESIONAL:")

display(
    df_resumen.style.format({
        "Trabajadores": "{:.0f}",
        "Salario_medio": "{:,.2f} €",
        "Edad_mediana": "{:.1f}"
    }, thousands=".", decimal=",", na_rep="-")
)

RESUMEN POR GRUPO PROFESIONAL:

In [ ]:
from google.colab import files

files.download("resultados_sprint8.xlsx")

Se ha creado una tabla resumen agrupando los empleados por grupo profesional mediante las funciones groupby() y agg() de Pandas.

Para cada grupo se ha calculado el número total de trabajadores, el salario medio mensual y la edad mediana.

La función mean() permite obtener el salario medio, mientras que median()`identifica la edad central de cada grupo, sin tener en cuenta los valores nulos.

Esta tabla sintetiza la información principal del dataset y facilita la comparación entre grupos profesionales. Además, servirá para generar el quinto archivo CSV solicitado en el ejercicio.