<a href="https://colab.research.google.com/github/Desireegit1/Desiree-Diaz-Python-Sprint-7-11/blob/main/SPRINT_8_DESIREE_DIAZ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
En aquest exercici has de realitzar una exploració inicial del DataFrame per respondre, com a mínim, a les següents preguntes:
•	» Quantes files i columnes té el dataset?
•	» Quin tipus de dades conté cada columna?
•	» Hi ha files duplicades?
•	» Les dades semblen coherents a primera vista?
•	» Detectes possibles problemes o inconsistències evidents?

In [13]:
# Importar Pandas
import pandas as pd

In [14]:
# Crear la función para cargar el Excel
def cargar_datos(archivo):
    df = pd.read_excel(archivo, header=3)
    return df

In [ ]:
# Cargar el archivo Excel
df = cargar_datos("sample_data/sprint8_complex.xlsx")

# Mostrar las primeras cinco filas // tienen caracteres incorrectos
display(df.head())

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1

In [ ]:
# Función para corregir caracteres extraños

def corregir_caracteres(df):

    df_corregido = df.copy()

    def corregir_texto(texto):
        if isinstance(texto, str):
            try:
                return texto.encode("latin1").decode("utf-8")
            except (UnicodeError, ValueError):
                return texto

        return texto

    df_corregido.columns = [
        corregir_texto(columna)
        for columna in df_corregido.columns
    ]

    for columna in df_corregido.select_dtypes(include="object").columns:
        df_corregido[columna] = df_corregido[columna].map(corregir_texto)

    return df_corregido

In [ ]:
# Función para corregir el símbolo del euro

def corregir_euros(df):

    df_corregido = df.copy()

    df_corregido["Salari mensual"] = (
        df_corregido["Salari mensual"]
        .str.replace("â‚¬", "€", regex=False)
        .str.replace("â‚", "€", regex=False)
    )

    return df_corregido

In [ ]:
# Crear una copia con los caracteres corregidos
df_corregido = corregir_caracteres(df)

# Corregir los símbolos del euro
df_corregido = corregir_euros(df_corregido)

# Mostrar una única tabla con todas las correcciones
display(df_corregido.head())

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 €",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 €",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,Tècnic IT,4.0,NaN,NaN,NaN,16.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 €",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 €",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1

In [ ]:
# Función para analizar las dimensiones
def analizar_dimensiones(df):
    filas = df.shape[0]
    columnas = df.shape[1]

    print("Número de filas:", filas)
    print("Número de columnas:", columnas)

In [ ]:
# Llamamos la funcion
analizar_dimensiones(df)

Número de filas: 1007
Número de columnas: 20

In [ ]:
# Analitzar el tipus de dades de cada columna del DataFrame per identificar si conté números enters, decimals o textos i detectar possibles tipus de dades incorrectes.

In [ ]:
# Función para analizar los tipos de datos
def analizar_tipos(df):
    tipos = df.dtypes

    print("Tipos de datos de cada columna:")
    print(tipos)

In [ ]:
# detectar filas duplicadas

In [ ]:
# Llamamos a la función
analizar_tipos(df)

Tipos de datos de cada columna:
Unnamed: 0                      int64
Nom                            object
Cognoms                        object
DNI                            object
País d'origen                  object
Ciutat                         object
Dia de Naixement              float64
Mes de Naixement              float64
Any de Naixement              float64
Gènere                         object
Salari mensual                 object
Fills                          object
No Fills                       object
Grup Professional              object
CÃ rrec                        object
Nombre_fills                  float64
Te_cotxe                       object
Km_anuals                     float64
Consum_mitja_L_100km          float64
Temperatura_mitjana_ciutat    float64
dtype: object

In [ ]:
# Función para detectar duplicados: esta función comprueba filas completamente idénticas, no si hay DNI repetidos. Eso lo podremos comprobar por separado.
def detectar_duplicados(df):
    duplicados = df.duplicated().sum()

    print("Número de filas duplicadas:", duplicados)

In [ ]:
# Llamamos a la función / NO hay duplicados
detectar_duplicados(df)

Número de filas duplicadas: 0

In [ ]:
# detectar valores nulos (NaN) / Revisar totes les columnes del DataFrame per identificar els valors absents.
# Contar el numero de valoress nulos de cada columna i mostrar els resultats per determinar quines variables necessiten una revisió posterior.

In [ ]:
# Función para detectar valores nulos
def detectar_nulos(df):
    nulos = df.isnull().sum()

    print("Valores nulos por columna:")
    print(nulos)

In [ ]:
# Llamamos a la función
detectar_nulos(df)

Valores nulos por columna:
Unnamed: 0                      0
Nom                             1
Cognoms                         1
DNI                             1
País d'origen                   1
Ciutat                          1
Dia de Naixement                1
Mes de Naixement                1
Any de Naixement                1
Gènere                         41
Salari mensual                  1
Fills                         588
No Fills                      422
Grup Professional               2
CÃ rrec                         2
Nombre_fills                  298
Te_cotxe                      349
Km_anuals                     692
Consum_mitja_L_100km          746
Temperatura_mitjana_ciutat     71
dtype: int64

In [ ]:
 CONCULUSION: Se han detectado valores nulos en varias columnas del conjunto de datos. Las variables con mayor cantidad de datos ausentes son Consum_mitja_L_100km, Km_anuals, Fills y No Fills.
Será necesario analizar si estos valores corresponden a información que no se aplica a determinados empleados o si se trata de datos incompletos.

In [ ]:
Analizar la coherencia de los datos
Ahora tenemos que comprobar si existen valores incorrectos o inconsistencias.

In [ ]:
# Analizar la coherencia de los datos

In [ ]:
# Función para analizar la coherencia
def analizar_coherencia(df):
    estadisticas = df.describe(include="all")

    print("Estadísticas descriptivas:")
    display(estadisticas)

In [ ]:
# Llamamos a la función
analizar_coherencia(df)

Estadísticas descriptivas:

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
count,1007.000000,1006,1006,1006,1006,1006,1006.000000,1006.000000,1006.000000,966,1006,419,585,1005,1005,709.000000,658,315.000000,261.000000,936.000000
unique,NaN,103,468,991,6,45,NaN,NaN,NaN,9,855,1,2,5,14,NaN,2,NaN,NaN,NaN
top,NaN,AdriÃ,Ferrer,90585882A,Espanya,Palma,NaN,NaN,NaN,D,n/d,True,True,Grup A,Data Analyst,NaN,False,NaN,NaN,NaN
freq,NaN,34,22,6,719,58,NaN,NaN,NaN,325,14,419,584,466,142,NaN,330,NaN,NaN,NaN
mean,503.000000,NaN,NaN,NaN,NaN,NaN,15.027833,8.556660,2002.229622,NaN,NaN,NaN,NaN,NaN,NaN,1.203103,NaN,55951.050794,11.024521,15.379167
std,290.840162,NaN,NaN,NaN,NaN,NaN,10.327436,14.298532,143.118077,NaN,NaN,NaN,NaN,NaN,NaN,1.389404,NaN,62095.437005,8.775557,7.276425
min,0.000000,NaN,NaN,NaN,NaN,NaN,-99.000000,0.000000,1940.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,-50.000000,0.500000,-10.000000
25%,251.500000,NaN,NaN,NaN,NaN,NaN,7.000000,3.250000,1969.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,22632.000000,4.700000,12.800000
50%,503.000000,NaN,NaN,NaN,NaN,NaN,15.000000,6.000000,1982.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,56135.000000,9.800000,15.500000
75%,754.500000,NaN,NaN,NaN,NaN,NaN,24.000000,10.000000,1995.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,80000.000000,13.600000,18.300000
max,1006.000000,NaN,NaN,NaN,NaN,NaN,32.000000,99.000000,3000.000000,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,1000000.000000,25.000000,42.000000

In [ ]:
Conclusión: los datos no son completamente coherentes y necesitarán limpieza antes de realizar un análisis fiable.
El análisis exploratorio ha permitido identificar diversas inconsistencias en el conjunto de datos. Se han detectado valores imposibles en las fechas de nacimiento, como días negativos, meses superiores a 12 y años futuros. También se observan valores negativos y extremos en los kilómetros anuales, diferentes categorías para representar el género y salarios almacenados como texto.
Además, existen valores nulos y posibles identificadores DNI repetidos. Por tanto, será necesario realizar una limpieza y validación de los datos antes de utilizarlos para obtener conclusiones.

In [ ]:
# Función para detectar DNI repetidos

def detectar_dni_duplicados(df):

    duplicados = df[
        df["DNI"].notna() &
        df["DNI"].duplicated(keep=False)
    ]

    print("Registros con DNI repetidos:", len(duplicados))

    display(duplicados[["Nom", "Cognoms", "DNI"]])

In [ ]:
# Llamamos a la función
detectar_dni_duplicados(df)

Registros con DNI repetidos: 24

          Nom          Cognoms        DNI
25       Sara            Serra  90585882A
36        Ida  Karlsen Eriksen  55283701C
40        Ida  Karlsen Eriksen  55283701C
89    Guillem      Pujol Costa  54013571W
104     Oriol      Vila Casals  90585882A
114       Pol            Serra  90585882A
142     Marta             Ruiz  54013571W
250      Laia     Navarro Vila  15909601K
281    Xavier            Vidal  90585882A
372      Alba           MuÃ±oz  97954019T
558    Alexia     PÃ©rez DÃ­az  49529438G
604      Laia          Navarro  15909601K
654     Oriol           GÃ³mez  16618423V
692    Alexia     PÃ©rez DÃ­az  49529438G
730   Claudia       Gil Ferrer  55297384F
754     Oriol           GÃ³mez  16618423V
757     Oriol           Ferrer  52590001R
758     Oriol           GÃ³mez  16618423V
759     Oriol           GÃ³mez  16618423V
913      Sara            Serra  90585882A
1000     Sara            Serra  90585882A
1002     Alba           MuÃ±oz  97954019T
1003  Claudia       Gil Ferrer  55297384F
1004    Oriol           Ferrer  52590001R

In [ ]:
# Función para analizar las categorías de género

def analizar_genero(df):
    categorias = df["Gènere"].value_counts(dropna=False)

    print("Categorías de género:")
    print(categorias)

In [ ]:
# Llamamos a la función
analizar_genero(df)

Categorías de género:
Gènere
D       325
H       280
Dona    120
F       107
Home     52
NaN      41
M        34
A        24
NC       23
??        1
Name: count, dtype: int64

In [ ]:
Se han identificado nueve categorías diferentes en la variable género, además de 41 valores nulos.
 Algunas categorías podrían representar el mismo concepto mediante diferentes abreviaturas o palabras, mientras que otras presentan significados ambiguos.
Será necesario revisar y estandarizar esta variable antes de realizar análisis estadísticos, evitando asignar significados sin comprobarlos.

In [ ]:
# FUNCIÓN PRINCIPAL

def main():

    # Cargar el archivo original
    df = cargar_datos("sample_data/sprint8_complex.xlsx")

    # Corregir caracteres para la presentación
    df_corregido = corregir_caracteres(df)
    df_corregido = corregir_euros(df_corregido)

    print("\n--- 1. DIMENSIONES ---")
    analizar_dimensiones(df)

    print("\n--- 2. PRIMERAS FILAS ---")
    mostrar_datos(df_corregido)

    print("\n--- 3. TIPOS DE DATOS ---")
    analizar_tipos(df)

    print("\n--- 4. FILAS DUPLICADAS ---")
    detectar_duplicados(df)

    print("\n--- 5. VALORES NULOS ---")
    detectar_nulos(df)

    print("\n--- 6. COHERENCIA DE LOS DATOS ---")
    analizar_coherencia(df_corregido)

    print("\n--- 7. DNI REPETIDOS ---")
    detectar_dni_duplicados(df_corregido)

    print("\n--- 8. CATEGORÍAS DE GÉNERO ---")
    analizar_genero(df)


# EJECUTAR EL PROGRAMA
main()

--- 1. DIMENSIONES ---
Número de filas: 1007
Número de columnas: 20

--- 2. PRIMERAS FILAS ---
Primeras cinco filas:

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 €",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 €",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,Tècnic IT,4.0,NaN,NaN,NaN,16.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 €",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 €",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1

--- 3. TIPOS DE DATOS ---
Tipos de datos de cada columna:
Unnamed: 0                      int64
Nom                            object
Cognoms                        object
DNI                            object
País d'origen                  object
Ciutat                         object
Dia de Naixement              float64
Mes de Naixement              float64
Any de Naixement              float64
Gènere                         object
Salari mensual                 object
Fills                          object
No Fills                       object
Grup Professional              object
CÃ rrec                        object
Nombre_fills                  float64
Te_cotxe                       object
Km_anuals                     float64
Consum_mitja_L_100km          float64
Temperatura_mitjana_ciutat    float64
dtype: object

--- 4. FILAS DUPLICADAS ---
Número de filas duplicadas: 0

--- 5. VALORES NULOS ---
Valores nulos por columna:
Unnamed: 0                      0
Nom                             1
Cognoms                         1
DNI                             1
País d'origen                   1
Ciutat                          1
Dia de Naixement                1
Mes de Naixement                1
Any de Naixement                1
Gènere                         41
Salari mensual                  1
Fills                         588
No Fills                      422
Grup Professional               2
CÃ rrec                         2
Nombre_fills                  298
Te_cotxe                      349
Km_anuals                     692
Consum_mitja_L_100km          746
Temperatura_mitjana_ciutat     71
dtype: int64

--- 6. COHERENCIA DE LOS DATOS ---
Estadísticas descriptivas:

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
count,1007.000000,1006,1006,1006,1006,1006,1006.000000,1006.000000,1006.000000,966,1006,419,585,1005,1005,709.000000,658,315.000000,261.000000,936.000000
unique,NaN,103,468,991,6,45,NaN,NaN,NaN,9,855,1,2,5,14,NaN,2,NaN,NaN,NaN
top,NaN,Adrià,Ferrer,90585882A,Espanya,Palma,NaN,NaN,NaN,D,n/d,True,True,Grup A,Data Analyst,NaN,False,NaN,NaN,NaN
freq,NaN,34,22,6,719,58,NaN,NaN,NaN,325,14,419,584,466,142,NaN,330,NaN,NaN,NaN
mean,503.000000,NaN,NaN,NaN,NaN,NaN,15.027833,8.556660,2002.229622,NaN,NaN,NaN,NaN,NaN,NaN,1.203103,NaN,55951.050794,11.024521,15.379167
std,290.840162,NaN,NaN,NaN,NaN,NaN,10.327436,14.298532,143.118077,NaN,NaN,NaN,NaN,NaN,NaN,1.389404,NaN,62095.437005,8.775557,7.276425
min,0.000000,NaN,NaN,NaN,NaN,NaN,-99.000000,0.000000,1940.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,-50.000000,0.500000,-10.000000
25%,251.500000,NaN,NaN,NaN,NaN,NaN,7.000000,3.250000,1969.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,22632.000000,4.700000,12.800000
50%,503.000000,NaN,NaN,NaN,NaN,NaN,15.000000,6.000000,1982.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,56135.000000,9.800000,15.500000
75%,754.500000,NaN,NaN,NaN,NaN,NaN,24.000000,10.000000,1995.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,80000.000000,13.600000,18.300000
max,1006.000000,NaN,NaN,NaN,NaN,NaN,32.000000,99.000000,3000.000000,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,1000000.000000,25.000000,42.000000

--- 7. DNI REPETIDOS ---
Registros con DNI repetidos: 24

          Nom          Cognoms        DNI
25       Sara            Serra  90585882A
36        Ida  Karlsen Eriksen  55283701C
40        Ida  Karlsen Eriksen  55283701C
89    Guillem      Pujol Costa  54013571W
104     Oriol      Vila Casals  90585882A
114       Pol            Serra  90585882A
142     Marta             Ruiz  54013571W
250      Laia     Navarro Vila  15909601K
281    Xavier            Vidal  90585882A
372      Alba            Muñoz  97954019T
558    Alexia       Pérez Díaz  49529438G
604      Laia          Navarro  15909601K
654     Oriol            Gómez  16618423V
692    Alexia       Pérez Díaz  49529438G
730   Claudia       Gil Ferrer  55297384F
754     Oriol            Gómez  16618423V
757     Oriol           Ferrer  52590001R
758     Oriol            Gómez  16618423V
759     Oriol            Gómez  16618423V
913      Sara            Serra  90585882A
1000     Sara            Serra  90585882A
1002     Alba            Muñoz  97954019T
1003  Claudia       Gil Ferrer  55297384F
1004    Oriol           Ferrer  52590001R

--- 8. CATEGORÍAS DE GÉNERO ---
Categorías de género:
Gènere
D       325
H       280
Dona    120
F       107
Home     52
NaN      41
M        34
A        24
NC       23
??        1
Name: count, dtype: int64

In [ ]:
Exercici 2:
Validacions bàsiques de les dades i decisions d'eliminació
🎯 Objectiu: assegurar que les dades compleixen unes condicions mínimes de qualitat i determinar quines files poden continuar sent analitzades i quines s'han de descartar.
En aquest exercici hauràs de validar aspectes clau del dataset que són crítics en qualsevol context real d'anàlisi de dades, prenent decisions justificades sobre la validesa o eliminació de registres.

Aspectes a validar:

» Existeixen identificadors únics (DNI) per a cada persona?
» Què faràs amb les files duplicades o registres repetits?
» Hi ha valors obligatoris que falten o informació incoherent?
» Detectes formats incorrectes, errors de codificació o valors impossibles?

In [4]:
# aunque el database lo heos cargado en el primer ejercicio, vuevoa cargar todo otra vez.
import pandas as pd

# Cargar el archivo Excel
df = pd.read_excel("sample_data/sprint8_complex.xlsx", header=3)

# Crear una copia para trabajar
df_limpio = df.copy()

print("Registros originales:", len(df_limpio))
print("Columnas:", len(df_limpio.columns))

Registros originales: 1007
Columnas: 20

In [5]:
# Mostramos los nombres de las columnas para detectar
# posibles errores de codificación y acentuación.

display(df_limpio.columns.to_frame(index=False))

                             0
0                   Unnamed: 0
1                          Nom
2                      Cognoms
3                          DNI
4                País d'origen
5                       Ciutat
6             Dia de Naixement
7             Mes de Naixement
8             Any de Naixement
9                       Gènere
10              Salari mensual
11                       Fills
12                    No Fills
13           Grup Professional
14                     CÃ rrec
15                Nombre_fills
16                    Te_cotxe
17                   Km_anuals
18        Consum_mitja_L_100km
19  Temperatura_mitjana_ciutat

In [6]:
# Mostramos nombres y apellidos para detectar
# posibles errores de codificación.

display(df_limpio[["Nom", "Cognoms"]].head(20))

        Nom            Cognoms
0     Joana        Gil Navarro
1      Marc             MuÃ±oz
2       Noa              Serra
3       Pol                Gil
4     David               Vila
5    Alexia               Puig
6     David        GÃ³mez Vila
7    Carmen             LÃ³pez
8      Nora  Andersen Pedersen
9      Alba            GarcÃ­a
10    Joana       Torres DÃ­az
11  Guillem              Vidal
12     Aina             PÃ©rez
13   Emilia           Hoffmann
14   Xavier             Casals
15   Carmen   HernÃ¡ndez Serra
16     Sara   HernÃ¡ndez Costa
17   Sigrid              Olsen
18      Nil   FernÃ¡ndez Vidal
19   AdriÃ              Ribera

In [7]:
# Mostramos los nombres de las columnas, para corregir los datos de codificacion y acentuacion
# FUNCIÓN: CORREGIR ERRORES DE CODIFICACIÓN

def corregir_texto(texto):

    if isinstance(texto, str):
        for codificacion in ["cp1252", "latin1"]:
            try:
                return texto.encode(codificacion).decode("utf-8")
            except (UnicodeError, ValueError):
                continue

    return texto


# Corregir nombres de columnas
df_limpio.columns = [
    corregir_texto(columna) for columna in df_limpio.columns
]

# Corregir los valores de texto
for columna in df_limpio.select_dtypes(include="object").columns:
    df_limpio[columna] = df_limpio[columna].map(corregir_texto)

# Comprobar resultados
display(df_limpio[["Nom", "Cognoms", "Salari mensual"]].head(20))

        Nom            Cognoms  Salari mensual
0     Joana        Gil Navarro         1,469 €
1      Marc              Muñoz         2,718 €
2       Noa              Serra      1358 euros
3       Pol                Gil         1,478 €
4     David               Vila         1,284 €
5    Alexia               Puig         2,069 €
6     David         Gómez Vila         2,349 €
7    Carmen              López         2,855 €
8      Nora  Andersen Pedersen         1,338 €
9      Alba             García         1,450 €
10    Joana        Torres Díaz           982 €
11  Guillem              Vidal         2,419 €
12     Aina              Pérez         3,672 €
13   Emilia           Hoffmann         1,003 €
14   Xavier             Casals  mil vuit-cents
15   Carmen    Hernández Serra         1,336 €
16     Sara    Hernández Costa           982 €
17   Sigrid              Olsen         1,385 €
18      Nil    Fernández Vidal         1,751 €
19    Adrià             Ribera       889 euros

In [10]:
# CORREGIR Y UNIFICAR LOS FORMATOS DE SALARIO

def corregir_salario(valor):

    if pd.isna(valor):
        return None

    valor = str(valor).strip().lower()

    # Corregir símbolos mal codificados
    valor = valor.replace("â‚¬", "€")

    # Convertir salarios escritos con palabras
    if valor == "mil vuit-cents":
        return 1800.0

    # Eliminar símbolos y palabras
    valor = valor.replace("euros", "")
    valor = valor.replace("€", "")
    valor = valor.replace(",", "")
    valor = valor.replace(" ", "")

    # Convertir a número
    return pd.to_numeric(valor, errors="coerce")


# Aplicamos la corrección de salarios
df_limpio["Salari mensual"] = (
    df_limpio["Salari mensual"].apply(corregir_salario)
)

# Comprobamos los resultados con el símbolo € y sin decimales
display(
    df_limpio[["Nom", "Cognoms", "Salari mensual"]]
    .head(20)
    .style.format({"Salari mensual": "{:.0f} €"})
)

In [11]:
# ELIMINAR DUPLICADOS EXACTOS

filas_antes = len(df_limpio)

columnas = df_limpio.columns.drop("Unnamed: 0")

df_limpio = df_limpio.drop_duplicates(
    subset=columnas,
    keep="first"
).copy()

print("Registros eliminados:", filas_antes - len(df_limpio))
print("Registros restantes:", len(df_limpio))

Registros eliminados: 4
Registros restantes: 1003

In [13]:
# Mostramos los nombres y apellidos para detectar errores de codificación

display(df_limpio[["Nom", "Cognoms"]].head(20))

        Nom            Cognoms
0     Joana        Gil Navarro
1      Marc              Muñoz
2       Noa              Serra
3       Pol                Gil
4     David               Vila
5    Alexia               Puig
6     David         Gómez Vila
7    Carmen              López
8      Nora  Andersen Pedersen
9      Alba             García
10    Joana        Torres Díaz
11  Guillem              Vidal
12     Aina              Pérez
13   Emilia           Hoffmann
14   Xavier             Casals
15   Carmen    Hernández Serra
16     Sara    Hernández Costa
17   Sigrid              Olsen
18      Nil    Fernández Vidal
19    Adrià             Ribera

In [ ]:
Después de corregir los problemas de codificación y los símbolos, hemos comprobado los registros duplicados del dataset.

Se han identificado y eliminado 4 registros duplicados, comparando todas las columnas excepto Unnamed: 0, que corresponde a un identificador auxiliar.

Hemos utilizado drop_duplicates(keep="first") para conservar la primera aparición de cada registro.

El dataset ha pasado de 1.007 a 1.003 registros.

In [14]:
# DETECTAR DNI DUPLICADOS

duplicados_dni = df_limpio[
    df_limpio["DNI"].notna() &
    df_limpio["DNI"].duplicated(keep=False)
]

print("Registros con DNI duplicado:", len(duplicados_dni))
print("DNI distintos repetidos:", duplicados_dni["DNI"].nunique())

display(duplicados_dni)

Registros con DNI duplicado: 16
DNI distintos repetidos: 5

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
25,25,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,993.000,NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
89,89,Guillem,Pujol Costa,54013571W,Espanya,A Coruña,17.0,7.0,1983.0,D,1.574,True,NaN,Grup B,Project lead,4.0,False,NaN,NaN,14.6
104,104,Oriol,Vila Casals,90585882A,Espanya,Madrid,30.0,9.0,1964.0,H,1987.000,NaN,True,Grup B,Responsable de vendes,0.0,False,NaN,NaN,13.5
114,114,Pol,Serra,90585882A,Espanya,Girona,4.0,12.0,1960.0,H,1178.000,NaN,True,Grup A,Data Analyst,NaN,False,NaN,NaN,16.2
142,142,Marta,Ruiz,54013571W,Espanya,Palma,24.0,5.0,1982.0,H,1276.000,True,True,Grup A,Analista,0.0,False,NaN,NaN,15.7
250,250,Laia,Navarro Vila,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,1235.000,True,True,Grup D,Analista junior,0.0,False,NaN,NaN,10.3
281,281,Xavier,Vidal,90585882A,Espanya,Alacant,2.0,7.0,1958.0,H,1179.000,NaN,NaN,Grup A,Tècnic IT,0.0,True,63574.0,6.0,16.8
558,558,Alexia,Pérez Díaz,49529438G,Espanya,Màlaga,12.0,10.0,1981.0,Dona,1176.000,NaN,True,Grup A,Data Analyst,0.0,False,NaN,NaN,38.0
604,604,Laia,Navarro,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,1676.000,True,False,Grup A,Analista,1.0,True,50.0,NaN,14.2
654,654,Oriol,Gómez,16618423V,Espanya,Madrid,10.0,1.0,1968.0,Home,1731.000,True,NaN,Grup B,Data analyst,4.0,NaN,NaN,NaN,NaN
692,692,Alexia,Pérez Díaz,49529438G,Espanya,Màlaga,12.0,10.0,1981.0,Dona,1663.000,NaN,True,Grup C,Cap de projecte,NaN,True,80000.0,10.7,16.9
754,754,Oriol,Gómez,16618423V,Espanya,Barcelona,10.0,1.0,1968.0,Home,2.358,True,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
758,758,Oriol,Gómez,16618423V,Espanya,Màlaga,10.0,1.0,1968.0,H,1879.000,True,NaN,Grup B,Data Analyst,4.0,False,NaN,NaN,NaN
759,759,Oriol,Gómez,16618423V,Espanya,Sevilla,10.0,1.0,1968.0,NaN,2000.000,NaN,NaN,Grup A,Responsable de vendes,5.0,NaN,NaN,NaN,20.7
913,913,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,Dona,1000.000,NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1000,1000,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,1073.000,NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8

In [15]:
# SEPARAR REGISTROS CON DNI DUPLICADOS

# Guardamos los registros para revisión
df_conflictivos = duplicados_dni.copy()

# Los excluimos provisionalmente del análisis
df_validado = df_limpio.drop(
    index=df_conflictivos.index
).copy()

print("Registros enviados a revisión:", len(df_conflictivos))
print("Registros restantes:", len(df_validado))

Registros enviados a revisión: 16
Registros restantes: 987

In [16]:
# DETECTAR REGISTROS CON INFORMACIÓN INSUFICIENTE

# Definimos los campos obligatorios
campos_clave = ["DNI", "Nom", "Cognoms"]

# Detectamos registros con algún campo obligatorio vacío
registros_incompletos = df_validado[
    df_validado[campos_clave].isna().any(axis=1)
]

# Mostramos los resultados
print("Registros con información insuficiente:", len(registros_incompletos))

display(registros_incompletos)

Registros con información insuficiente: 1

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
1005,1005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# DETECTAR FECHAS DE NACIMIENTO INCORRECTAS

fechas_incorrectas = df_validado[
    (~df_validado["Dia de Naixement"].between(1, 31)) |
    (~df_validado["Mes de Naixement"].between(1, 12)) |
    (df_validado["Any de Naixement"] > 2026) |
    (df_validado["Any de Naixement"] < 1900)
]

print("Registros con fechas incorrectas:", len(fechas_incorrectas))

display(fechas_incorrectas[
    ["Nom", "Cognoms", "DNI",
     "Dia de Naixement", "Mes de Naixement",
     "Any de Naixement"]
])

Registros con fechas incorrectas: 78

,Nom,Cognoms,DNI,Dia de Naixement,Mes de Naixement,Any de Naixement
9,Alba,García,75181648S,32.0,0.0,1940.0
39,Guillem,Vila,92874006W,0.0,99.0,3000.0
41,Paul,Richard Laurent,43567615Z,32.0,99.0,2019.0
47,Aina,Fernández,38468360C,-5.0,0.0,3000.0
53,Aina,Serra,29226889H,0.0,0.0,2019.0
...,...,...,...,...,...,...
926,David,Pérez,52298598B,-5.0,0.0,2019.0
958,Ida,Johansen Kristiansen,41407343V,32.0,99.0,2019.0
981,Giulia,Romano,34747698K,32.0,0.0,2026.0
996,Lucía,Roca Vila,21702378D,32.0,0.0,1940.0
1006,???,###,XXXX,-99.0,99.0,3000.0

In [22]:
# REVISAR REGISTRO CON DATOS INCOHERENTES

display(df_validado.loc[[1006]])

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
1006,1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,NaN,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

In [23]:
# ELIMINAR REGISTRO CON INFORMACIÓN IRRECUPERABLE

filas_antes = len(df_validado)

df_validado = df_validado.drop(index=1006).copy()

print("Registros eliminados:", filas_antes - len(df_validado))
print("Registros restantes:", len(df_validado))

Registros eliminados: 1
Registros restantes: 985

In [26]:
print("=" * 55)
print("INFORME FINAL - EJERCICIO 2")
print("=" * 55)

print("Registros originales:", len(df))
print("Duplicados exactos eliminados:", 4)
print("Registros con DNI duplicado:", len(duplicados_dni))
print("DNI distintos repetidos:", duplicados_dni["DNI"].nunique())
print("Registros irrecuperables eliminados:", 2)
print("Registros con fechas incorrectas detectados:", len(fechas_incorrectas))
print("Registros finales válidos para continuar:", len(df_validado))

print("=" * 55)

=======================================================
INFORME FINAL - EJERCICIO 2
=======================================================
Registros originales: 1007
Duplicados exactos eliminados: 4
Registros con DNI duplicado: 16
DNI distintos repetidos: 5
Registros irrecuperables eliminados: 2
Registros con fechas incorrectas detectados: 78
Registros finales válidos para continuar: 985
=======================================================

In [ ]:
Hemos obtenido los siguientes resultados:

Registros originales: 1.007.

Duplicados exactos eliminados: 4.

Registros con DNI repetidos: 16, correspondientes a 5 DNI distintos, apartados para revisión por presentar información contradictoria.

Registros irrecuperables eliminados: 2 (índices 1005 y 1006).

Registros con posibles fechas incorrectas: 78 detectados inicialmente.

También hemos corregido los errores de codificación, acentuación y representación de salarios.

Conclusión: el dataset ha pasado de 1.007 a 985 registros disponibles para continuar el análisis. Los registros con fechas incorrectas no se han eliminado automáticamente, ya que pueden contener información útil.

No hemos imputado valores. Las decisiones de eliminación se han justificado siguiendo los criterios de calidad establecidos en el enunciado.

In [ ]:
Exercici 3: Transformacions necessàries i preparació del dataset
🎯 Objectiu: preparar el dataset perquè sigui coherent, analitzable i estructuralment correcte abans de realitzar qualsevol anàlisi descriptiva.

In [ ]:
Partiremos del dataset validado en el ejercicio 2. Primero normalizaremos las categorías que representan el mismo concepto. Después comprobaremos la coherencia de la información sobre vehículos e hijos y unificaremos las columnas redundantes. Finalmente completaremos los valores ausentes de temperatura y salario mediante criterios estadísticos justificados, conservando todos los registros.

In [ ]:
Paso	Qué haremos	Columna
1	Normalizar categorías	Gènere, Càrrec, Grup Professional
2	Comprobar coche, kilómetros y consumo	Te_cotxe, Km_anuals, Consum_mitja_L_100km
3	Unificar la información de hijos	Fills, No Fills, Nombre_fills
4	Completar temperaturas ausentes	Temperatura_mitjana_ciutat
5	Completar salarios ausentes	Salari mensual
6	Mostrar el resultado final	DataFrame transformado

In [29]:
# SPRINT 8 - NIVEL 1 - EJERCICIO 3
# NORMALIZAR VALORES CATEGÓRICOS

df_transformado = df_validado.copy()

# Normalizar género
df_transformado["Gènere"] = df_transformado["Gènere"].replace({
    "D": "Dona",
    "F": "Dona",
    "H": "Home",
    "M": "Home"
})
# Normalizar cargo
df_transformado["Càrrec"] = (
    df_transformado["Càrrec"]
    .str.strip()
    .str.lower()
    .str.title()
)

# Mostrar resultados
print("Géneros:")
print(df_transformado["Gènere"].value_counts(dropna=False))

print("\nCargos:")
print(df_transformado["Càrrec"].value_counts(dropna=False))

Géneros:
Gènere
Dona    541
Home    358
NaN      39
A        24
NC       23
Name: count, dtype: int64

Cargos:
Càrrec
Data Analyst             156
Tècnic It                128
Senior Analyst           122
Responsable De Vendes    121
Analista                 112
Cap De Projecte          106
Analista Junior          106
Administratiu            102
Project Lead              17
Analyst                    9
Admin.                     6
Name: count, dtype: int64

In [30]:
# PASO 2 - IDENTIFICAR COLUMNAS DE VEHÍCULOS

print(df_transformado.columns.tolist())

['Unnamed: 0', 'Nom', 'Cognoms', 'DNI', "País d'origen", 'Ciutat', 'Dia de Naixement', 'Mes de Naixement', 'Any de Naixement', 'Gènere', 'Salari mensual', 'Fills', 'No Fills', 'Grup Professional', 'Càrrec', 'Nombre_fills', 'Te_cotxe', 'Km_anuals', 'Consum_mitja_L_100km', 'Temperatura_mitjana_ciutat']

In [31]:
# PASO 2 - COMPROBAR DATOS DE VEHÍCULOS

# Ver los valores de la columna coche
print(df_transformado["Te_cotxe"].value_counts(dropna=False))

# Personas con kilómetros o consumo, pero sin coche declarado
incoherencias_coche = df_transformado[
    (df_transformado["Km_anuals"].notna() |
     df_transformado["Consum_mitja_L_100km"].notna()) &
    (df_transformado["Te_cotxe"].isna())
]

# Personas con consumo, pero sin kilómetros
sin_kilometros = df_transformado[
    df_transformado["Consum_mitja_L_100km"].notna() &
    df_transformado["Km_anuals"].isna()
]

print("\nSin coche declarado, pero con datos de vehículo:", len(incoherencias_coche))
print("Con consumo, pero sin kilómetros:", len(sin_kilometros))


#no modificamos los datos. Primero identificamos las incoherencias para decidir cómo corregirlas sin inventar kilómetros ni consumos.
#conservar los dos registros y dejar los kilómetros como NaN, porque no podemos calcularlos a partir del consumo medio.

Te_cotxe
NaN      342
True     323
False    320
Name: count, dtype: int64

Sin coche declarado, pero con datos de vehículo: 0
Con consumo, pero sin kilómetros: 2

In [33]:
# Comprobar personas con datos de vehículo que declaran no tener coche

sin_coche = df_transformado[
    (df_transformado["Te_cotxe"] == False) &
    (
        df_transformado["Km_anuals"].notna() |
        df_transformado["Consum_mitja_L_100km"].notna()
    )
]

print("Personas sin coche, pero con kilómetros o consumo:", len(sin_coche))
display(sin_coche[["Te_cotxe", "Km_anuals", "Consum_mitja_L_100km"]])

Personas sin coche, pero con kilómetros o consumo: 4

    Te_cotxe  Km_anuals  Consum_mitja_L_100km
270    False        0.0                   NaN
698    False        0.0                   NaN
743    False        0.0                   NaN
922    False        0.0                   NaN

In [34]:
# Personas sin coche: kilómetros y consumo no aplicables

df_transformado.loc[
    df_transformado["Te_cotxe"] == False,
    ["Km_anuals", "Consum_mitja_L_100km"]
] = float("nan")

# Comprobar los dos casos con consumo, pero sin kilómetros
display(sin_kilometros[
    ["Te_cotxe", "Km_anuals", "Consum_mitja_L_100km"]
])

   Te_cotxe  Km_anuals  Consum_mitja_L_100km
4      True        NaN                  11.8
60     True        NaN                  25.0

In [ ]:

#se normalizan los datos de personas sin coche y se mantienen los dos registros con consumo pero sin kilometraje, ya que no existe información suficiente para completar ese valor.
# mantenemos Km_anuals = NaN porque no podemos calcular los kilómetros sin información adicional.

In [35]:
# PASO 3 - COMPROBAR INFORMACIÓN SOBRE HIJOS

print("Fills:")
print(df_transformado["Fills"].value_counts(dropna=False))

print("\nNo Fills:")
print(df_transformado["No Fills"].value_counts(dropna=False))

print("\nNombre_fills:")
print(df_transformado["Nombre_fills"].value_counts(dropna=False))

Fills:
Fills
NaN     574
True    411
Name: count, dtype: int64

No Fills:
No Fills
True    572
NaN     413
Name: count, dtype: int64

Nombre_fills:
Nombre_fills
0.0    301
NaN    294
1.0    170
2.0     79
4.0     77
3.0     64
Name: count, dtype: int64

In [36]:
# Comprobar contradicciones en la información de hijos

incoherencias_hijos = df_transformado[
    ((df_transformado["Fills"] == True) &
     (df_transformado["Nombre_fills"] == 0)) |
    ((df_transformado["No Fills"] == True) &
     (df_transformado["Nombre_fills"] > 0))
]

print("Registros con contradicciones:", len(incoherencias_hijos))

display(incoherencias_hijos[
    ["Fills", "No Fills", "Nombre_fills"]
])

Registros con contradicciones: 52

    Fills No Fills  Nombre_fills
11   True     True           1.0
17   True     True           0.0
38    NaN     True           2.0
128   NaN     True           2.0
155  True     True           0.0
165  True     True           1.0
168  True     True           0.0
205  True     True           1.0
219  True     True           0.0
221  True     True           1.0
239  True     True           4.0
257  True     True           0.0
280  True     True           0.0
283  True     True           0.0
289  True     True           0.0
293  True     True           0.0
320  True     True           0.0
326  True     True           0.0
330  True     True           1.0
354  True     True           0.0
379   NaN     True           1.0
387   NaN     True           4.0
422   NaN     True           4.0
430   NaN     True           2.0
440  True     True           0.0
441  True     True           3.0
453  True     True           0.0
496  True     True           0.0
531  True     True           3.0
571  True     True           0.0
578  True     True           3.0
595  True     True           0.0
601  True     True           0.0
627  True     True           0.0
667  True     True           0.0
678  True     True           0.0
740  True     True           0.0
742  True     True           0.0
744   NaN     True           2.0
767  True     True           0.0
795  True     True           0.0
800  True     True           0.0
803  True     True           0.0
841  True     True           0.0
854  True     True           0.0
866  True     True           2.0
889  True     True           0.0
898  True     True           0.0
937   NaN     True           3.0
947  True     True           1.0
954   NaN     True           1.0
987  True     True           0.0

In [37]:
# Completar el número de hijos cuando falte

df_transformado.loc[
    df_transformado["Nombre_fills"].isna() &
    (df_transformado["No Fills"] == True) &
    (df_transformado["Fills"] != True),
    "Nombre_fills"
] = 0

# Conservar solo la columna del número de hijos
df_transformado = df_transformado.drop(
    columns=["Fills", "No Fills"]
)

# Comprobar resultado
print(df_transformado["Nombre_fills"].value_counts(dropna=False))
print("Registros totales:", len(df_transformado))

Nombre_fills
0.0    563
1.0    170
2.0     79
4.0     77
3.0     64
NaN     32
Name: count, dtype: int64
Registros totales: 985

In [ ]:
conservamos el número declarado cuando existe. Si no existe y la persona indica únicamente que no tiene hijos, asignamos 0.
Si sabemos que tiene hijos, pero no cuántos, mantenemos NaN porque no podemos inventar la cantidad.

In [38]:
# PASO 4 - COMPROBAR TEMPERATURAS

print("Temperaturas nulas:",
      df_transformado["Temperatura_mitjana_ciutat"].isna().sum())

print("\nTipo de dato:")
print(df_transformado["Temperatura_mitjana_ciutat"].dtype)

print("\nTemperaturas por ciudad:")
display(
    df_transformado.groupby("Ciutat")["Temperatura_mitjana_ciutat"]
    .agg(["count", "median"])
)

Temperaturas nulas: 66

Tipo de dato:
float64

Temperaturas por ciudad:

                            count  median
Ciutat
A Coruña                       43   13.80
Alacant                        39   18.00
Barcelona                      51   16.60
Bergen                         10    7.85
Berlin                          6    9.85
Bilbao                         42   13.80
Bologna                        11   13.30
Bordeaux                       10   12.90
Düsseldorf                      5    9.20
Firenze                        17   14.30
Frankfurt                       6   10.85
Genova                         12   15.90
Girona                         39   14.50
Hamburg                         9    8.90
Köln                            3    9.50
Las Palmas de Gran Canaria     43   21.70
Leipzig                         5   12.50
Lille                          10   12.05
Lyon                            4   10.45
Madrid                         39   15.40
Marseille                      12   14.60
Milano                         13   12.80
Murcia                         46   18.85
Màlaga                         47   19.00
München                         4    8.70
Nantes                         12   12.70
Napoli                         18   15.70
Nice                           11   16.50
Oslo                           14    7.10
Palma                          51   18.00
Paris                           7   12.60
Roma                           15   15.40
Sevilla                        46   19.15
Stavanger                       8    7.85
Stuttgart                       7   10.20
Tarragona                      42   16.80
Torino                         15   14.40
Toulouse                       14   13.65
Tromsø                          4    2.95
Trondheim                       6    3.95
Valladolid                     43   12.20
València                       32   17.30
Venezia                         4   14.20
Zaragoza                       44   15.20

In [39]:
# PASO 4 - IMPUTAR TEMPERATURAS POR CIUDAD

df_transformado["Temperatura_mitjana_ciutat"] = (
    df_transformado["Temperatura_mitjana_ciutat"].fillna(
        df_transformado.groupby("Ciutat")["Temperatura_mitjana_ciutat"]
        .transform("median")
    )
)

# Comprobar resultado
print("Temperaturas nulas restantes:",
      df_transformado["Temperatura_mitjana_ciutat"].isna().sum())

print("Registros totales:", len(df_transformado))

Temperaturas nulas restantes: 0
Registros totales: 985

In [ ]:
se imputan las temperaturas ausentes utilizando la mediana de cada ciudad, porque representa mejor las condiciones climáticas locales y reduce la influencia de valores extremos.

In [40]:
# PASO 5 - REVISAR SALARIOS

print("Salarios nulos:",
      df_transformado["Salari mensual"].isna().sum())

print("\nTipo de dato:")
print(df_transformado["Salari mensual"].dtype)

print("\nSalario mediano por cargo:")
display(
    df_transformado.groupby("Càrrec")["Salari mensual"]
    .agg(["count", "median"])
)

Salarios nulos: 27

Tipo de dato:
float64

Salario mediano por cargo:

                       count  median
Càrrec
Admin.                     6  1627.5
Administratiu            101  1215.0
Analista                 110  1266.5
Analista Junior          104  1156.5
Analyst                    9  1212.0
Cap De Projecte          102  1617.5
Data Analyst             152  1308.5
Project Lead              17  1177.0
Responsable De Vendes    118  1297.0
Senior Analyst           114  1459.0
Tècnic It                125  1341.0

In [41]:
# PASO 5 - COMPLETAR SALARIOS POR CARGO

df_transformado["Salari mensual"] = (
    df_transformado["Salari mensual"].fillna(
        df_transformado.groupby("Càrrec")["Salari mensual"]
        .transform("median")
    )
)

# Comprobar resultado
print("Salarios nulos restantes:",
      df_transformado["Salari mensual"].isna().sum())

print("Registros totales:", len(df_transformado))

Salarios nulos restantes: 0
Registros totales: 985

In [ ]:
se imputan los 27 salarios ausentes mediante la mediana salarial del cargo profesional, conservando los salarios originales y evitando que valores extremos influyan excesivamente en la imputación.

In [42]:
# PASO 6 - COMPROBACIÓN FINAL

print("=" * 50)
print("INFORME FINAL - EJERCICIO 3")
print("=" * 50)

# 1. Dimensiones
print("Registros finales:", len(df_transformado))
print("Columnas finales:", len(df_transformado.columns))

# 2. Valores nulos
print("\nVALORES NULOS:")
print(df_transformado.isna().sum())

# 3. Comprobar información de hijos
print("\nColumna de hijos:")
print("Nombre_fills" in df_transformado.columns)

# 4. Comprobar temperaturas y salarios
print("\nTemperaturas nulas:",
      df_transformado["Temperatura_mitjana_ciutat"].isna().sum())

print("Salarios nulos:",
      df_transformado["Salari mensual"].isna().sum())

# 5. Comprobar duplicados
print("\nDNI duplicados:",
      df_transformado["DNI"].duplicated().sum())

# 6. Mostrar tabla final
print("\nDATASET TRANSFORMADO:")
display(df_transformado.head())

==================================================
INFORME FINAL - EJERCICIO 3
==================================================
Registros finales: 985
Columnas finales: 18

VALORES NULOS:
Unnamed: 0                      0
Nom                             0
Cognoms                         0
DNI                             0
País d'origen                   0
Ciutat                          0
Dia de Naixement                0
Mes de Naixement                0
Any de Naixement                0
Gènere                         39
Salari mensual                  0
Grup Professional               0
Càrrec                          0
Nombre_fills                   32
Te_cotxe                      342
Km_anuals                     679
Consum_mitja_L_100km          728
Temperatura_mitjana_ciutat      0
dtype: int64

Columna de hijos:
True

Temperaturas nulas: 0
Salarios nulos: 0

DNI duplicados: 0

DATASET TRANSFORMADO:

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,1469.0,Grup B,Cap De Projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,Home,2718.0,Grup C,Senior Analyst,0.0,True,19496.0,10.4,18.7
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,Dona,1358.0,Grup A,Tècnic It,4.0,NaN,NaN,NaN,16.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,Home,1478.0,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,1284.0,Grup B,Administratiu,0.0,True,NaN,11.8,13.1

In [ ]:
CONCLUSION: Hemos normalizado las categorías, revisado la coherencia de los datos de vehículos, unificado la información de hijos y completado las temperaturas y salarios ausentes utilizando medianas por ciudad y cargo, respectivamente.
Los valores desconocidos que no podemos deducir de forma fiable se mantienen como nulos.

In [ ]:
Exercici 4: Primeres anàlisis descriptives
🎯 Objectiu: obtenir una primera visió global del dataset un cop s'han aplicat les transformacions bàsiques, mitjançant estadístiques descriptives i comparacions simples entre grups rellevants.

In [ ]:
Partimos de df_transformado, la tabla que hemos preparado en el ejercicio 3, con 985 registros, los salarios corregidos y los valores nulos de salario imputados.
Tabla de salarios por género: media, mediana, mínimo y máximo.
Tabla de salario medio por género y país, con medias en los márgenes y colores.
Extra: comparación mediante porcentajes y ratios salariales.

In [43]:

# PASO 1 - ESTADÍSTICAS SALARIALES POR GÉNERO : las categorías Dona, Home, A y NC. Los géneros nulos no se incluyen en la agrupación por defecto.

tabla_salarios = (
    df_transformado.groupby("Gènere")["Salari mensual"]
    .agg(
        Media="mean",
        Mediana="median",
        Minimo="min",
        Maximo="max"
    )
    .sort_values("Media", ascending=False)
)

# Mostrar salarios en euros con dos decimales
display(tabla_salarios.style.format("{:,.2f} €"))

In [ ]:
La tabla descriptiva muestra diferencias salariales entre los géneros. El grupo Home presenta el salario medio más alto (1.587,17 €),
mientras que Dona presenta el más bajo (1.371,08 €), con una diferencia de 216,09 €, equivalente aproximadamente al 15,76 % del salario medio de Dona.

Sin embargo, estas diferencias deben interpretarse con precaución, porque los grupos tienen tamaños distintos y pueden incluir diferentes cargos profesionales.
Además, existen salarios mínimos anormalmente bajos.

Por tanto, los valores absolutos permiten describir las diferencias, pero los porcentajes y las ratios salariales ayudan a compararlas de forma relativa.
No podemos concluir que exista discriminación salarial únicamente a partir de esta tabla.

In [44]:
# EXTRA - DIFERENCIAS SALARIALES EN PORCENTAJES

media_dona = tabla_salarios.loc["Dona", "Media"]

tabla_extra = tabla_salarios[["Media"]].copy()

# Porcentaje respecto al salario medio de Dona
tabla_extra["Diferencia_%"] = (
    (tabla_extra["Media"] / media_dona - 1) * 100
)

# Ratio respecto al salario medio de Dona
tabla_extra["Ratio"] = tabla_extra["Media"] / media_dona

display(
    tabla_extra.style.format({
        "Media": "{:,.2f} €",
        "Diferencia_%": "{:+.2f} %",
        "Ratio": "{:.2f}"
    })
)

In [ ]:
El análisis porcentual confirma que el grupo Home presenta un salario medio un 15,76 % superior al de Dona, mientras que NC presenta un 10,38 % más y A un 2,18 % más.

Los porcentajes y ratios permiten expresar las diferencias salariales de forma relativa, facilitando la comparación entre grupos.
Sin embargo, no tienen en cuenta las diferencias de tamaño ni de composición profesional de cada grupo.

Por tanto, los resultados describen diferencias salariales, pero no permiten determinar sus causas.

In [46]:
# PASO 2 - SALARIO MEDIO POR GÉNERO Y PAÍS

tabla_paises = pd.pivot_table(
    df_transformado,
    values="Salari mensual",
    index="Gènere",
    columns="País d'origen",
    aggfunc="mean",
    margins=True,
    margins_name="Media general"
)

display(
    tabla_paises.style
    .format("{:,.2f} €", na_rep="—")
    .background_gradient(cmap="Blues", axis=None)
)

In [ ]:
La tabla cruzada permite comparar los salarios medios según el género y el país de origen.

El salario medio general es de 1.457,08 €. Por países, Noruega presenta la media más elevada (1.500,42 €), mientras que Francia registra la más baja (1.409,49 €).

Por género, Home presenta el salario medio más alto (1.587,17 €) y Dona el más bajo (1.371,08 €).

El formato condicional facilita identificar visualmente los salarios más elevados. No obstante, algunas combinaciones carecen de datos y existen valores salariales atípicos, por lo que las comparaciones deben interpretarse con precaución.

Estos resultados describen las diferencias observadas, pero no permiten determinar sus causas.

In [ ]:
Nivell 2 - Anàlisi amb dades enriquides i estructures múltiples

In [ ]:
Exercici 1: Enriquiment mitjançant datasets externs
🎯 Objectiu: ampliar el dataset principal integrant informació contextual externa i avaluar l'impacte analític de les decisions de fusió.
» Integrar el dataset principal amb:
El dataset contextual de ciutats.
La política salarial definida en format JSON
» Calcular un increment salarial total combinant:
Grup professional.
Situació familiar.
Franja d'edat.
Cost de vida de la ciutat.
» Identificar quins registres no poden rebre algun dels ajustos i explicar-ne el motiu.
» Decidir, de manera raonada, com tractar aquests casos en el càlcul del salari ajustat, justificando l'impacte analític de la decisió presa.

In [ ]:
Paso 1. Cargar los archivos externos
Leer el CSV de ciudades con pd.read_csv() y el JSON salarial con json.load().



Paso 2. Comprobar la compatibilidad
Comparar nombres de ciudades, países y grupos profesionales entre los archivos. Identificar valores que no coinciden.



Paso 3. Unir los datasets
Incorporar los datos de ciudades a df_transformado mediante merge(), sin perder registros.



Paso 4. Identificar los datos faltantes
Comprobar qué empleados no tienen información suficiente para aplicar algún ajuste salarial y explicar el motivo.



Paso 5. Calcular los incrementos salariales
Aplicar las reglas del JSON:
- Grupo profesional.
- Hijos.
- Franja de edad.
- Coste de vida de la ciudad.
Revisaremos también las reglas de transporte, el límite del 15 % y el umbral salarial de 800 €.



Paso 6. Decidir cómo tratar los casos incompletos
Justificar qué hacemos cuando falta información: no inventaremos incrementos y distinguiremos los cálculos completos de los parciales.



Paso 7. Calcular el salario ajustado
Aplicar la fórmula:
\[
\text{Salario ajustado}=\text{Salario actual}\times\left(1+\frac{\text{Incremento \%}}{100}\right)
\]

Comprobar que se respetan las reglas de la política salarial.



Paso 8. Informe final y conclusiones
Mostrar los registros procesados, los casos incompletos y el impacto de nuestras decisiones sobre los resultados.

In [76]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 1
# PASO 1 - CARGAR ARCHIVOS EXTERNOS
# ==========================================================

import pandas as pd
import json

# 1. Cargar el archivo CSV de ciudades
df_ciudades = pd.read_csv(
    "sample_data/ciutats_context.csv",
    encoding="cp1252"
)

# 2. Cargar el archivo JSON de política salarial
with open("sample_data/politica_salarial.json", encoding="utf-8") as archivo:
    politica = json.load(archivo)

# 3. Mostrar dimensiones y primeras filas
print("DIMENSIONES DEL DATASET DE CIUDADES:")
print(df_ciudades.shape)

print("\nPRIMERAS CINCO FILAS:")
display(df_ciudades.head())

# 4. Mostrar política salarial
print("\nPOLÍTICA SALARIAL:")
print(politica)

DIMENSIONES DEL DATASET DE CIUDADES:
(36, 5)

PRIMERAS CINCO FILAS:

      Ciutat     País  Cost_vida_index  Transport_public_score  Clima_tipus
0  Barcelona  Espanya               78                     8.5  Mediterrani
1     Madrid  Espanya               75                     8.0  Continental
2   València  Espanya               70                     7.5  Mediterrani
3    Sevilla  Espanya               65                     7.0  Mediterrani
4     Bilbao  Espanya               72                     7.8      Oceànic

POLÍTICA SALARIAL:
{'base_increment_by_group': {'Grup A': 5.0, 'Grup B': 3.5, 'Grup C': 2.0, 'Grup D': 8.0}, 'children_adjustment': {'has_children': 1.5, 'no_children': 0.0}, 'age_adjustment': {'18-29': 0.0, '30-44': 1.0, '45-59': 2.0, '60+': 1.5}, 'cost_of_living_adjustment': {'low': 0.0, 'medium': 1.0, 'high': 2.0}, 'transport_adjustment': {'low': 0.5, 'medium': 0.0, 'high': -0.5}, 'rules': {'max_total_increment_percent': 15, 'min_salary_threshold': 800}}

In [77]:
# VER EL CONTENIDO COMPLETO DEL CSV

display(df_ciudades)

,Ciutat,País,Cost_vida_index,Transport_public_score,Clima_tipus
0,Barcelona,Espanya,78,8.5,Mediterrani
1,Madrid,Espanya,75,8.0,Continental
2,València,Espanya,70,7.5,Mediterrani
3,Sevilla,Espanya,65,7.0,Mediterrani
4,Bilbao,Espanya,72,7.8,Oceànic
5,Zaragoza,Espanya,68,7.0,Continental
6,Murcia,Espanya,60,6.5,Mediterrani
7,Palma,Espanya,73,7.2,Mediterrani
8,Girona,Espanya,66,6.8,Mediterrani
9,Tarragona,Espanya,67,6.9,Mediterrani
10,A Coru\u00f1a,Espanya,69,7.1,Oceànic
11,Valladolid,Espanya,64,6.7,Continental
12,Alacant,Espanya,68,7.0,Mediterrani
13,Las Palmas de Gran Canaria,Espanya,62,6.8,Subtropical
14,Paris,França,85,9.0,Oceànic
15,Marseille,França,72,7.4,Mediterrani
16,Lyon,França,74,7.6,Continental
17,Bordeaux,França,73,7.2,Oceànic
18,Lille,França,71,7.3,Continental
19,Milano,Itàlia,80,7.5,Continental
20,Roma,Itàlia,78,7.6,Mediterrani
21,Torino,Itàlia,74,7.2,Continental
22,Genova,Itàlia,72,6.9,Mediterrani
23,Venezia,Itàlia,79,7.0,Mediterrani
24,Napoli,Itàlia,65,6.5,Mediterrani
25,Firenze,Itàlia,77,7.1,Continental
26,Berlin,Alemanya,76,8.5,Continental
27,Munchen,Alemanya,82,8.0,Continental
28,Hamburg,Alemanya,78,8.1,Oceànic
29,Frankfurt,Alemanya,80,8.3,Continental
30,Stuttgart,Alemanya,79,7.9,Continental
31,Leipzig,Alemanya,70,7.2,Continental
32,Oslo,Noruega,90,9.2,Fred
33,Bergen,Noruega,85,8.8,Oceànic
34,Paris,Estats Units,88,6.0,Continental
35,Valencia,Veneçuela,55,5.5,Tropical

In [78]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 1
# PASO 2 - COMPROBAR COMPATIBILIDAD
# ==========================================================

# 1. Comprobar las columnas de ambos datasets
print("COLUMNAS DEL DATASET PRINCIPAL:")
print(df_transformado.columns.tolist())

print("\nCOLUMNAS DEL DATASET DE CIUDADES:")
print(df_ciudades.columns.tolist())

# 2. Buscar ciudades que no aparecen en el CSV
ciudades_sin_coincidencia = (
    set(df_transformado["Ciutat"].dropna())
    - set(df_ciudades["Ciutat"].dropna())
)

print("\nCIUDADES SIN COINCIDENCIA:")
print(ciudades_sin_coincidencia)

# 3. Buscar grupos profesionales que no aparecen en el JSON
grupos_sin_coincidencia = (
    set(df_transformado["Grup Professional"].dropna())
    - set(politica["base_increment_by_group"].keys())
)

print("\nGRUPOS PROFESIONALES SIN COINCIDENCIA:")
print(grupos_sin_coincidencia)

COLUMNAS DEL DATASET PRINCIPAL:
['Unnamed: 0', 'Nom', 'Cognoms', 'DNI', "País d'origen", 'Ciutat', 'Dia de Naixement', 'Mes de Naixement', 'Any de Naixement', 'Gènere', 'Salari mensual', 'Grup Professional', 'Càrrec', 'Nombre_fills', 'Te_cotxe', 'Km_anuals', 'Consum_mitja_L_100km', 'Temperatura_mitjana_ciutat']

COLUMNAS DEL DATASET DE CIUDADES:
['Ciutat', 'País', 'Cost_vida_index', 'Transport_public_score', 'Clima_tipus']

CIUDADES SIN COINCIDENCIA:
{'Nice', 'A Coruña', 'Stavanger', 'Tromsø', 'Màlaga', 'Köln', 'Düsseldorf', 'München', 'Nantes', 'Toulouse', 'Trondheim', 'Bologna'}

GRUPOS PROFESIONALES SIN COINCIDENCIA:
set()

In [ ]:
Resultados
- Grupos profesionales: set() significa que todos los grupos del dataset principal están definidos en el JSON. Correcto.
- Ciudades: hay 12 nombres que no coinciden con el CSV externo: Nice, A Coruña, Stavanger, Tromsø, Málaga, Köln, Düsseldorf, München, Nantes, Toulouse, Trondheim y Bologna.
Esto no significa necesariamente que falten esas ciudades. Algunas pueden estar escritas de forma diferente en ambos archivos.

In [ ]:
dentificado las 12 ciudades que no coinciden y sus países.
Esto es importante porque, si hacemos el merge() directamente, los empleados de esas ciudades podrían quedarse sin información sobre el coste de vida.

In [79]:
# PASO 2.4 - NORMALIZAR NOMBRES DE CIUDADES /En el CSV aparece como A Coru\u00f1a (con los caracteres \u00f1 escritos literalmente).

df_enriquecido = df_transformado.copy()

# Corregir nombres para que coincidan con el CSV
df_enriquecido["Ciutat"] = df_enriquecido["Ciutat"].replace({
    "München": "Munchen",
    "A Coruña": r"A Coru\u00f1a"
})

# Comprobar las ciudades que siguen sin coincidencia
ciudades_pendientes = (
    set(df_enriquecido["Ciutat"].dropna())
    - set(df_ciudades["Ciutat"].dropna())
)

print("CIUDADES TODAVÍA SIN COINCIDENCIA:")
print(sorted(ciudades_pendientes))

CIUDADES TODAVÍA SIN COINCIDENCIA:
['Bologna', 'Düsseldorf', 'Köln', 'Màlaga', 'Nantes', 'Nice', 'Stavanger', 'Toulouse', 'Tromsø', 'Trondheim']

In [80]:
# ==========================================================
# PASO 3 - UNIR DATASET PRINCIPAL Y CIUDADES
# ==========================================================

df_enriquecido = df_enriquecido.merge(
    df_ciudades,
    left_on=["Ciutat", "País d'origen"],
    right_on=["Ciutat", "País"],
    how="left",
    validate="many_to_one",
    indicator=True
)

# Comprobar dimensiones
print("DIMENSIONES DEL DATASET ENRIQUECIDO:")
print(df_enriquecido.shape)

# Comprobar coincidencias
print("\nRESULTADO DE LA UNIÓN:")
print(df_enriquecido["_merge"].value_counts())

# Mostrar primeras filas
display(df_enriquecido.head())

DIMENSIONES DEL DATASET ENRIQUECIDO:
(985, 23)

RESULTADO DE LA UNIÓN:
_merge
both          855
left_only     130
right_only      0
Name: count, dtype: int64

,Unnamed: 0,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,...,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat,País,Cost_vida_index,Transport_public_score,Clima_tipus,_merge
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,...,3.0,True,32108.0,25.0,10.1,Espanya,64.0,6.7,Continental,both
1,1,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,Home,...,0.0,True,19496.0,10.4,18.7,Espanya,68.0,7.0,Mediterrani,both
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,Dona,...,4.0,NaN,NaN,NaN,16.7,Espanya,68.0,7.0,Mediterrani,both
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,Home,...,2.0,False,NaN,NaN,18.3,Espanya,65.0,7.0,Mediterrani,both
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,...,0.0,True,NaN,11.8,13.1,Espanya,72.0,7.8,Oceànic,both

In [81]:
# ==========================================================
# PASO 4 - IDENTIFICAR REGISTROS SIN DATOS DE CIUDAD
# ==========================================================

# 1. Seleccionar empleados sin coincidencia
sin_contexto = df_enriquecido[
    df_enriquecido["_merge"] == "left_only"
]

# 2. Contar empleados afectados
print("EMPLEADOS SIN INFORMACIÓN CONTEXTUAL:")
print(len(sin_contexto))

# 3. Contar empleados afectados por ciudad
print("\nEMPLEADOS AFECTADOS POR CIUDAD:")

display(
    sin_contexto["Ciutat"].value_counts()
)

EMPLEADOS SIN INFORMACIÓN CONTEXTUAL:
130

EMPLEADOS AFECTADOS POR CIUDAD:

Ciutat
Màlaga        53
Toulouse      15
Nantes        12
Bologna       11
Nice          11
Stavanger      9
Trondheim      6
Düsseldorf     5
Tromsø         4
Köln           4
Name: count, dtype: int64

In [82]:
# ==========================================================
# PASO 4.2 - COMPROBAR DATOS NECESARIOS
# ==========================================================

# 1. Comprobar valores vacíos
columnas = [
    "Grup Professional",
    "Nombre_fills",
    "Any de Naixement",
    "Cost_vida_index"
]

print("VALORES VACÍOS POR COLUMNA:")
print(df_enriquecido[columnas].isna().sum())

# 2. Comprobar los grupos profesionales
print("\nGRUPOS PROFESIONALES:")
print(df_enriquecido["Grup Professional"].value_counts(dropna=False))

# 3. Comprobar el número de hijos
print("\nNÚMERO DE HIJOS:")
print(df_enriquecido["Nombre_fills"].value_counts(dropna=False))

VALORES VACÍOS POR COLUMNA:
Grup Professional      0
Nombre_fills          32
Any de Naixement       0
Cost_vida_index      130
dtype: int64

GRUPOS PROFESIONALES:
Grup Professional
Grup A    456
Grup B    350
Grup C    139
Grup D     40
Name: count, dtype: int64

NÚMERO DE HIJOS:
Nombre_fills
0.0    563
1.0    170
2.0     79
4.0     77
3.0     64
NaN     32
Name: count, dtype: int64

In [83]:
# ==========================================================
# PASO 4.3 - COMPROBAR FECHAS DE NACIMIENTO
# ==========================================================

columnas_fecha = [
    "Dia de Naixement",
    "Mes de Naixement",
    "Any de Naixement"
]

# 1. Comprobar valores vacíos
print("VALORES VACÍOS EN LAS FECHAS:")
print(df_enriquecido[columnas_fecha].isna().sum())

# 2. Comprobar los años de nacimiento
print("\nAÑOS DE NACIMIENTO:")
print(df_enriquecido["Any de Naixement"].describe())

# 3. Comprobar las fechas completas
fechas = pd.to_datetime(
    df_enriquecido["Any de Naixement"].astype("Int64").astype(str) + "-" +
    df_enriquecido["Mes de Naixement"].astype("Int64").astype(str) + "-" +
    df_enriquecido["Dia de Naixement"].astype("Int64").astype(str),
    errors="coerce"
)

print("\nFECHAS INVÁLIDAS O INCOMPLETAS:")
print(fechas.isna().sum())

VALORES VACÍOS EN LAS FECHAS:
Dia de Naixement    0
Mes de Naixement    0
Any de Naixement    0
dtype: int64

AÑOS DE NACIMIENTO:
count     985.000000
mean     2001.737056
std       141.033327
min      1940.000000
25%      1969.000000
50%      1982.000000
75%      1995.000000
max      3000.000000
Name: Any de Naixement, dtype: float64

FECHAS INVÁLIDAS O INCOMPLETAS:
77

In [ ]:
aunque las columnas de nacimiento no tienen valores vacíos, existen fechas incorrectas que impiden calcular la edad de algunos empleados.. Utilizaremos las fechas válidas para calcular la edad y dejaremos el ajuste por edad como no calculable cuando la fecha sea incorrecta.
Así cumplimos el enunciado: identificar la información insuficiente, justificar nuestra decisión y explicar su impacto en el salario ajustado.

In [84]:
# ==========================================================
# PASO 5 - CALCULAR EDADES Y FRANJAS DE EDAD / podemos calcular el ajuste por edad para 908 empleados. Los otros 77 conservarán el ajuste como desconocido.
# ==========================================================

# 1. Guardar las fechas de nacimiento
df_enriquecido["Fecha_nacimiento"] = fechas

# 2. Calcular la edad a fecha 18/10/2026
fecha_referencia = pd.Timestamp("2026-10-18")

df_enriquecido["Edad"] = (
    fecha_referencia.year
    - df_enriquecido["Fecha_nacimiento"].dt.year
    - (
        fecha_referencia.strftime("%m%d")
        < df_enriquecido["Fecha_nacimiento"].dt.strftime("%m%d")
    )
)

# 3. Descartar edades imposibles o inferiores a 18 años
df_enriquecido.loc[
    (df_enriquecido["Edad"] < 18) |
    (df_enriquecido["Edad"] > 100),
    "Edad"
] = float("nan")

# 4. Asignar franjas de edad
def clasificar_edad(edad):

    if pd.isna(edad):
        return None
    elif edad < 30:
        return "18-29"
    elif edad < 45:
        return "30-44"
    elif edad < 60:
        return "45-59"
    else:
        return "60+"

df_enriquecido["Franja_edad"] = (
    df_enriquecido["Edad"].apply(clasificar_edad)
)

# 5. Mostrar resultados
print("EMPLEADOS POR FRANJA DE EDAD:")
print(df_enriquecido["Franja_edad"].value_counts(dropna=False))

display(
    df_enriquecido[
        ["Nom", "Fecha_nacimiento", "Edad", "Franja_edad"]
    ].head(10)
)

EMPLEADOS POR FRANJA DE EDAD:
Franja_edad
30-44    299
45-59    280
60+      174
18-29    155
None      77
Name: count, dtype: int64

      Nom Fecha_nacimiento  Edad Franja_edad
0   Joana       1958-03-23  68.0         60+
1    Marc       1960-11-08  65.0         60+
2     Noa       1961-04-27  65.0         60+
3     Pol       1985-10-13  41.0       30-44
4   David       1965-11-29  60.0         60+
5  Alexia       1978-08-01  48.0       45-59
6   David       1971-09-25  55.0       45-59
7  Carmen       1962-09-08  64.0         60+
8    Nora       1963-03-08  63.0         60+
9    Alba              NaT   NaN        None

In [85]:
# ==========================================================
# PASO 6 - APLICAR INCREMENTOS SALARIALES
# ==========================================================

# 1. Incremento por grupo profesional
df_enriquecido["Incremento_grupo"] = (
    df_enriquecido["Grup Professional"].map(
        politica["base_increment_by_group"]
    )
)

# 2. Incremento por hijos
def incremento_hijos(numero_hijos):

    if pd.isna(numero_hijos):
        return None
    elif numero_hijos > 0:
        return politica["children_adjustment"]["has_children"]
    else:
        return politica["children_adjustment"]["no_children"]

df_enriquecido["Incremento_hijos"] = (
    df_enriquecido["Nombre_fills"].apply(incremento_hijos)
)

# 3. Incremento por edad
df_enriquecido["Incremento_edad"] = (
    df_enriquecido["Franja_edad"].map(
        politica["age_adjustment"]
    )
)

# 4. Comprobar resultados
print("VALORES VACÍOS EN LOS INCREMENTOS:")
print(
    df_enriquecido[
        ["Incremento_grupo", "Incremento_hijos", "Incremento_edad"]
    ].isna().sum()
)

display(
    df_enriquecido[
        ["Nom", "Grup Professional", "Incremento_grupo",
         "Nombre_fills", "Incremento_hijos",
         "Franja_edad", "Incremento_edad"]
    ].head(10)
)

VALORES VACÍOS EN LOS INCREMENTOS:
Incremento_grupo     0
Incremento_hijos    32
Incremento_edad     77
dtype: int64

,Nom,Grup Professional,Incremento_grupo,Nombre_fills,Incremento_hijos,Franja_edad,Incremento_edad
0,Joana,Grup B,3.5,3.0,1.5,60+,1.5
1,Marc,Grup C,2.0,0.0,0.0,60+,1.5
2,Noa,Grup A,5.0,4.0,1.5,60+,1.5
3,Pol,Grup B,3.5,2.0,1.5,30-44,1.0
4,David,Grup B,3.5,0.0,0.0,60+,1.5
5,Alexia,Grup B,3.5,0.0,0.0,45-59,2.0
6,David,Grup B,3.5,0.0,0.0,45-59,2.0
7,Carmen,Grup C,2.0,4.0,1.5,60+,1.5
8,Nora,Grup B,3.5,0.0,0.0,60+,1.5
9,Alba,Grup A,5.0,4.0,1.5,None,NaN

In [ ]:
Pero nuestro CSV contiene Cost_vida_index, un índice numérico, no las categorías low, medium y high.
Por tanto, antes de aplicar los porcentajes necesitamos saber cómo convertir ese índice en categorías. El JSON no especifica los límites, así que tendremos que definirlos y justificar nuestra decisión.

In [86]:
# ==========================================================
# PASO 7.1 - ANALIZAR EL ÍNDICE DE COSTE DE VIDA
# ==========================================================

# 1. Estadísticas del índice
print("ESTADÍSTICAS DEL COSTE DE VIDA:")
print(df_ciudades["Cost_vida_index"].describe())

# 2. Mostrar ciudades e índices
print("\nCOSTE DE VIDA POR CIUDAD:")

display(
    df_ciudades[
        ["Ciutat", "País", "Cost_vida_index"]
    ].sort_values("Cost_vida_index")
)

ESTADÍSTICAS DEL COSTE DE VIDA:
count    36.000000
mean     73.333333
std       7.844926
min      55.000000
25%      68.000000
50%      73.000000
75%      78.250000
max      90.000000
Name: Cost_vida_index, dtype: float64

COSTE DE VIDA POR CIUDAD:

                        Ciutat          País  Cost_vida_index
35                    Valencia     Veneçuela               55
6                       Murcia       Espanya               60
13  Las Palmas de Gran Canaria       Espanya               62
11                  Valladolid       Espanya               64
24                      Napoli        Itàlia               65
3                      Sevilla       Espanya               65
8                       Girona       Espanya               66
9                    Tarragona       Espanya               67
12                     Alacant       Espanya               68
5                     Zaragoza       Espanya               68
10               A Coru\u00f1a       Espanya               69
31                     Leipzig      Alemanya               70
2                     València       Espanya               70
18                       Lille        França               71
15                   Marseille        França               72
22                      Genova        Itàlia               72
4                       Bilbao       Espanya               72
17                    Bordeaux        França               73
7                        Palma       Espanya               73
21                      Torino        Itàlia               74
16                        Lyon        França               74
1                       Madrid       Espanya               75
26                      Berlin      Alemanya               76
25                     Firenze        Itàlia               77
20                        Roma        Itàlia               78
28                     Hamburg      Alemanya               78
0                    Barcelona       Espanya               78
30                   Stuttgart      Alemanya               79
23                     Venezia        Itàlia               79
29                   Frankfurt      Alemanya               80
19                      Milano        Itàlia               80
27                     Munchen      Alemanya               82
14                       Paris        França               85
33                      Bergen       Noruega               85
34                       Paris  Estats Units               88
32                        Oslo       Noruega               90

In [87]:
# PASO 7.2 - CLASIFICAR EL COSTE DE VIDA

def clasificar_coste(indice):

    if pd.isna(indice):
        return None
    elif indice < 68:
        return "low"
    elif indice <= 78:
        return "medium"
    else:
        return "high"

# Crear categoría de coste de vida
df_enriquecido["Categoria_coste"] = (
    df_enriquecido["Cost_vida_index"].apply(clasificar_coste)
)

# Aplicar incrementos del JSON
df_enriquecido["Incremento_coste"] = (
    df_enriquecido["Categoria_coste"].map(
        politica["cost_of_living_adjustment"]
    )
)

# Comprobar resultados
print("EMPLEADOS POR CATEGORÍA:")
print(df_enriquecido["Categoria_coste"].value_counts(dropna=False))

print("\nINCREMENTOS SIN CALCULAR:")
print(df_enriquecido["Incremento_coste"].isna().sum())

EMPLEADOS POR CATEGORÍA:
Categoria_coste
medium    492
low       294
None      130
high       69
Name: count, dtype: int64

INCREMENTOS SIN CALCULAR:
130

In [89]:
# ==========================================================
# PASO 8 - CALCULAR EL SALARIO AJUSTADO
# ==========================================================

# 1. Seleccionar los cuatro incrementos
columnas_incrementos = [
    "Incremento_grupo",
    "Incremento_hijos",
    "Incremento_edad",
    "Incremento_coste"
]

# 2. Calcular el incremento total
df_enriquecido["Incremento_total"] = (
    df_enriquecido[columnas_incrementos].sum(
        axis=1, min_count=4
    )
)

# 3. Aplicar el límite máximo del 15 %
limite = politica["rules"]["max_total_increment_percent"]

df_enriquecido["Incremento_total"] = (
    df_enriquecido["Incremento_total"].clip(upper=limite)
)

# 4. Calcular el salario ajustado
df_enriquecido["Salario_ajustado"] = (
    df_enriquecido["Salari mensual"] *
    (1 + df_enriquecido["Incremento_total"] / 100)
)

# 5. Mostrar resultados
print("SALARIOS CALCULADOS:")
print(df_enriquecido["Salario_ajustado"].notna().sum())

print("\nSALARIOS PENDIENTES:")
print(df_enriquecido["Salario_ajustado"].isna().sum())

display(
    df_enriquecido[
        ["Nom", "Salari mensual",
         "Incremento_total", "Salario_ajustado"]
    ].head(10).style.format({
        "Salari mensual": "{:,.2f} €",
        "Incremento_total": "{:.2f} %",
        "Salario_ajustado": "{:,.2f} €"
    }, na_rep="—")
)

SALARIOS CALCULADOS:
759

SALARIOS PENDIENTES:
226

In [ ]:
Se ha enriquecido el dataset principal de 985 empleados mediante la integración del archivo CSV de ciudades europeas y la política salarial definida en JSON.

Durante el proceso se han detectado diferencias en los nombres de algunas ciudades, que se han corregido para facilitar la integración. Sin embargo, 130 empleados no disponen de información contextual sobre el coste de vida.

También se han identificado 32 empleados sin información sobre el número de hijos y 77 con fechas de nacimiento inválidas.

Para calcular los incrementos salariales se han utilizado cuatro factores: grupo profesional, situación familiar, franja de edad y coste de vida. Se ha aplicado el límite máximo del 15 % establecido en la política salarial.

Resultados:

759 empleados tienen un salario ajustado calculado.

226 empleados quedan pendientes por información insuficiente.

Se ha decidido no sustituir los datos desconocidos por valores inventados. Esta decisión reduce el número de salarios calculados, pero evita presentar estimaciones incompletas como resultados definitivos.

La clasificación del coste de vida se ha realizado mediante los percentiles 25 y 75 del CSV, dado que la política salarial no establece los límites numéricos de las categorías.

Limitaciones: el cálculo realizado utiliza los cuatro factores solicitados expresamente en el ejercicio. La política JSON también incluye ajustes por transporte y un umbral salarial mínimo de 800 €, que no se han aplicado. Por tanto, los resultados son válidos para el modelo de cuatro factores adoptado, pero no representan una aplicación completa de todas las reglas del JSON.

In [ ]:
Exercici 2: Reestructuració del dataset
🎯 Objectiu: preparar el dataset per a anàlisis comparatives i/o visuals. Convertir informació dispersa en format llarg:
Salaris
Mobilitat
Context climàtic etc
Reestructurar el dataset utilitzant melt() per convertir-lo a format llarg, definint prèviament:
les columnes que actuen com a identificadores (per exemple: persona, ciutat, grup professional, gènere, etc.).
les columnes que passen a representar valors mesurats (per exemple: salaris, mobilitat, variables contextuals).
» Analitzar per què el format llarg és més adequat per:
realitzar comparacions entre diferents tipus de variables.
calcular estadístics agregats.

In [90]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 2
# PASO 1 - SELECCIONAR COLUMNAS
# ==========================================================

# Columnas identificadoras
identificadores = [
    "DNI",
    "Nom",
    "Ciutat",
    "Grup Professional",
    "Gènere"
]

# Variables que transformaremos a formato largo
variables = [
    "Salari mensual",
    "Salario_ajustado",
    "Km_anuals",
    "Consum_mitja_L_100km",
    "Temperatura_mitjana_ciutat"
]

# Comprobar que las columnas existen
print("COLUMNAS IDENTIFICADORAS:")
print(identificadores)

print("\nVARIABLES MEDIDAS:")
print(variables)

# Mostrar una muestra del dataset
display(
    df_enriquecido[identificadores + variables].head()
)

COLUMNAS IDENTIFICADORAS:
['DNI', 'Nom', 'Ciutat', 'Grup Professional', 'Gènere']

VARIABLES MEDIDAS:
['Salari mensual', 'Salario_ajustado', 'Km_anuals', 'Consum_mitja_L_100km', 'Temperatura_mitjana_ciutat']

,DNI,Nom,Ciutat,Grup Professional,Gènere,Salari mensual,Salario_ajustado,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,66722344X,Joana,Valladolid,Grup B,Dona,1469.0,1564.485,32108.0,25.0,10.1
1,48840994W,Marc,Alacant,Grup C,Home,2718.0,2840.310,19496.0,10.4,18.7
2,14308421X,Noa,Alacant,Grup A,Dona,1358.0,1480.220,NaN,NaN,16.7
3,58586340F,Pol,Sevilla,Grup B,Home,1478.0,1566.680,NaN,NaN,18.3
4,82070937P,David,Bilbao,Grup B,Dona,1284.0,1361.040,NaN,11.8,13.1

In [91]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 2
# PASO 2 - TRANSFORMAR A FORMATO LARGO
# ==========================================================

df_largo = df_enriquecido.melt(
    id_vars=identificadores,
    value_vars=variables,
    var_name="Variable",
    value_name="Valor"
)

# Comprobar dimensiones
print("DIMENSIONES DEL DATASET ORIGINAL:")
print(df_enriquecido.shape)

print("\nDIMENSIONES DEL DATASET LARGO:")
print(df_largo.shape)

# Mostrar las primeras filas
display(df_largo.head(10))

DIMENSIONES DEL DATASET ORIGINAL:
(985, 33)

DIMENSIONES DEL DATASET LARGO:
(4925, 7)

,DNI,Nom,Ciutat,Grup Professional,Gènere,Variable,Valor
0,66722344X,Joana,Valladolid,Grup B,Dona,Salari mensual,1469.0
1,48840994W,Marc,Alacant,Grup C,Home,Salari mensual,2718.0
2,14308421X,Noa,Alacant,Grup A,Dona,Salari mensual,1358.0
3,58586340F,Pol,Sevilla,Grup B,Home,Salari mensual,1478.0
4,82070937P,David,Bilbao,Grup B,Dona,Salari mensual,1284.0
5,25014631B,Alexia,Las Palmas de Gran Canaria,Grup B,Dona,Salari mensual,2069.0
6,36998038E,David,Palma,Grup B,Dona,Salari mensual,2349.0
7,47376585K,Carmen,Barcelona,Grup C,Home,Salari mensual,2855.0
8,37289414J,Nora,Stavanger,Grup B,Dona,Salari mensual,1338.0
9,75181648S,Alba,Las Palmas de Gran Canaria,Grup A,Home,Salari mensual,1450.0

In [92]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 2
# PASO 3 - COMPROBAR VALORES NULOS
# ==========================================================

# Contar valores nulos por variable
nulos = df_largo.groupby("Variable")["Valor"].apply(
    lambda x: x.isna().sum()
)

print("VALORES NULOS POR VARIABLE:")
print(nulos)

# Comprobar número de registros por variable
print("\nREGISTROS POR VARIABLE:")
print(df_largo["Variable"].value_counts())

VALORES NULOS POR VARIABLE:
Variable
Consum_mitja_L_100km          728
Km_anuals                     679
Salari mensual                  0
Salario_ajustado              226
Temperatura_mitjana_ciutat      0
Name: Valor, dtype: int64

REGISTROS POR VARIABLE:
Variable
Salari mensual                985
Salario_ajustado              985
Km_anuals                     985
Consum_mitja_L_100km          985
Temperatura_mitjana_ciutat    985
Name: count, dtype: int64

In [93]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 2
# PASO 4 - ESTADÍSTICAS AGRUPADAS
# ==========================================================

# Calcular la media de cada variable por grupo profesional
estadisticas = df_largo.groupby(
    ["Grup Professional", "Variable"]
)["Valor"].mean().round(2)

print("MEDIA POR GRUPO PROFESIONAL Y VARIABLE:")
display(estadisticas.reset_index())

MEDIA POR GRUPO PROFESIONAL Y VARIABLE:

   Grup Professional                    Variable     Valor
0             Grup A        Consum_mitja_L_100km     11.30
1             Grup A                   Km_anuals  60486.08
2             Grup A              Salari mensual   1022.60
3             Grup A            Salario_ajustado   1090.26
4             Grup A  Temperatura_mitjana_ciutat     15.40
5             Grup B        Consum_mitja_L_100km     10.64
6             Grup B                   Km_anuals  54626.73
7             Grup B              Salari mensual   1550.52
8             Grup B            Salario_ajustado   1637.10
9             Grup B  Temperatura_mitjana_ciutat     15.39
10            Grup C        Consum_mitja_L_100km     10.43
11            Grup C                   Km_anuals  52899.79
12            Grup C              Salari mensual   2221.03
13            Grup C            Salario_ajustado   2268.72
14            Grup C  Temperatura_mitjana_ciutat     15.47
15            Grup D        Consum_mitja_L_100km     14.05
16            Grup D                   Km_anuals  45968.31
17            Grup D              Salari mensual   2811.08
18            Grup D            Salario_ajustado   3235.53
19            Grup D  Temperatura_mitjana_ciutat     15.37

In [94]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 2
# CONCLUSIONES FINALES
# ==========================================================

print("CONCLUSIONES DEL EJERCICIO 2")
print("=" * 50)

print("1. El dataset original tenía 985 filas y 33 columnas.")

print("2. Con melt() hemos obtenido 4925 filas y 7 columnas.")

print("3. El formato ancho facilita consultar todos los datos de un empleado.")

print("4. El formato largo facilita agrupar y comparar una misma variable.")

print("5. Con groupby() podemos calcular medias por grupo profesional.")

print("6. Los valores nulos se han conservado sin sustituirlos por cero.")

print("7. No debemos mezclar variables con unidades diferentes.")

CONCLUSIONES DEL EJERCICIO 2
==================================================
1. El dataset original tenía 985 filas y 33 columnas.
2. Con melt() hemos obtenido 4925 filas y 7 columnas.
3. El formato ancho facilita consultar todos los datos de un empleado.
4. El formato largo facilita agrupar y comparar una misma variable.
5. Con groupby() podemos calcular medias por grupo profesional.
6. Los valores nulos se han conservado sin sustituirlos por cero.
7. No debemos mezclar variables con unidades diferentes.

In [ ]:
En este ejercicio hemos utilizado la función melt() de Pandas para transformar el dataset de formato ancho a formato largo, pasando de 985 filas y 33 columnas a 4.925 filas y 7 columnas.
Esta transformación permite organizar los salarios, los datos de movilidad y las variables climáticas en una estructura más adecuada para realizar comparaciones y calcular estadísticas por grupo profesional mediante groupby().
También hemos comprobado que se conservan los valores nulos, por lo que no se pierde información durante la transformación.

In [ ]:
Exercici 3: Creació de variables derivades (Feature Engineering)

🎯 Objectiu: generar noves variables derivades a partir de la informació existent i avaluar-ne la qualitat analítica.
Tot i que algunes variables de base (com l’edat o el salari) ja han estat introduïdes en exercicis anteriors, en aquest nivell no es valora la seva creació tècnica,
sinó la capacitat de transformar-les en indicadors més informatius, l
a detecció de casos límit o incoherents i la reflexió sobre la utilitat real de les variables generades en un context analític.
Crear almenys 3 variables derivades.
» Justificar:
La seva utilitat analítica.
Les decisions preses.
» Detectar casos límit o incoherents generats per les noves variables.

In [95]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 3
# PASO 1 - COMPROBAR COLUMNAS
# ==========================================================

print("COLUMNAS DISPONIBLES:")
print(df_enriquecido.columns.tolist())

# Comprobar los datos que utilizaremos
columnas = [
    "Salari mensual",
    "Nombre_fills",
    "Cost_vida_index",
    "Edad"
]

for columna in columnas:
    print(columna, ":", columna in df_enriquecido.columns)

COLUMNAS DISPONIBLES:
['Unnamed: 0', 'Nom', 'Cognoms', 'DNI', "País d'origen", 'Ciutat', 'Dia de Naixement', 'Mes de Naixement', 'Any de Naixement', 'Gènere', 'Salari mensual', 'Grup Professional', 'Càrrec', 'Nombre_fills', 'Te_cotxe', 'Km_anuals', 'Consum_mitja_L_100km', 'Temperatura_mitjana_ciutat', 'País', 'Cost_vida_index', 'Transport_public_score', 'Clima_tipus', '_merge', 'Fecha_nacimiento', 'Edad', 'Franja_edad', 'Incremento_grupo', 'Incremento_hijos', 'Incremento_edad', 'Categoria_coste', 'Incremento_coste', 'Incremento_total', 'Salario_ajustado']
Salari mensual : True
Nombre_fills : True
Cost_vida_index : True
Edad : True

In [99]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 3
# PASO 2 - ÍNDICE DE DEPENDENCIA FAMILIAR
# ==========================================================

# Crear una copia del dataset original
df_derivadas = df_enriquecido.copy()

# Crear el índice de dependencia familiar
# Sumamos 1 para evitar dividir entre cero cuando no tiene hijos
df_derivadas["Indice_dependencia_familiar"] = (
    df_derivadas["Salari mensual"] /
    (df_derivadas["Nombre_fills"] + 1)
)

# Mostrar resultados con formato de euros
display(
    df_derivadas[
        ["Nom", "Salari mensual", "Nombre_fills",
         "Indice_dependencia_familiar"]
    ].head(10).style.format({
        "Salari mensual": "{:,.0f} €",
        "Nombre_fills": "{:.0f}",
        "Indice_dependencia_familiar": "{:,.2f} €"
    }, na_rep="—")
)

In [97]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 3
# PASO 3 - COMPROBAR CASOS LÍMITE
# ==========================================================

# Empleados sin hijos
print("EMPLEADOS SIN HIJOS:")
print((df_derivadas["Nombre_fills"] == 0).sum())

# Empleados sin información sobre hijos
print("\nVALORES NULOS:")
print(df_derivadas["Nombre_fills"].isna().sum())

# Empleados con número de hijos negativo
print("\nVALORES NEGATIVOS:")
print((df_derivadas["Nombre_fills"] < 0).sum())

# Resultados nulos del índice
print("\nÍNDICES NO CALCULADOS:")
print(df_derivadas["Indice_dependencia_familiar"].isna().sum())

EMPLEADOS SIN HIJOS:
563

VALORES NULOS:
32

VALORES NEGATIVOS:
0

ÍNDICES NO CALCULADOS:
32

In [100]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 3
# PASO 4 - RATIO SALARIO / COSTE DE VIDA
# Comparar salarios según el coste de vida de cada ciudad
# ==========================================================

# Crear la segunda variable derivada
df_derivadas["Ratio_salario_coste_vida"] = (
    df_derivadas["Salari mensual"] /
    df_derivadas["Cost_vida_index"].replace(0, float("nan"))
)

# Mostrar resultados con formato
display(
    df_derivadas[
        ["Nom", "Ciutat", "Salari mensual",
         "Cost_vida_index", "Ratio_salario_coste_vida"]
    ].head(10).style.format({
        "Salari mensual": "{:,.0f} €",
        "Cost_vida_index": "{:.0f}",
        "Ratio_salario_coste_vida": "{:.2f}"
    }, na_rep="—")
)

In [103]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 3
# PASO 5 - COMPROBAR CASOS LÍMITE
# ==========================================================

print("COSTE DE VIDA SIN DATOS:")
print(df_derivadas["Cost_vida_index"].isna().sum())

print("\nCOSTE DE VIDA IGUAL A CERO:")
print((df_derivadas["Cost_vida_index"] == 0).sum())

print("\nCOSTE DE VIDA NEGATIVO:")
print((df_derivadas["Cost_vida_index"] < 0).sum())

print("\nRATIOS NO CALCULADAS:")
print(df_derivadas["Ratio_salario_coste_vida"].isna().sum())

COSTE DE VIDA SIN DATOS:
130

COSTE DE VIDA IGUAL A CERO:
0

COSTE DE VIDA NEGATIVO:
0

RATIOS NO CALCULADAS:
130

In [104]:
# ==========================================================
# PASO 6 - PESO DE RESPONSABILIDAD FAMILIAR
# ==========================================================

# Crear la tercera variable derivada
df_derivadas["Peso_responsabilidad_familiar"] = (
    df_derivadas["Nombre_fills"] * df_derivadas["Edad"]
)

# Mostrar resultados
display(
    df_derivadas[
        ["Nom", "Nombre_fills", "Edad",
         "Peso_responsabilidad_familiar"]
    ].head(10).style.format({
        "Nombre_fills": "{:.0f}",
        "Edad": "{:.0f}",
        "Peso_responsabilidad_familiar": "{:.0f}"
    }, na_rep="—")
)

In [ ]:
combinamos dos características familiares en un único indicador para realizar comparaciones exploratorias.
 pero no mide realmente la responsabilidad familiar. Por ejemplo, tener 60 años y dos hijos adultos no implica necesariamente mayor dependencia que tener 30 años y dos hijos pequeños.
 los empleados sin hijos tienen un resultado de 0, mientras que Alba tiene la edad vacía y, por tanto, no podemos calcular su indicador.

In [105]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 3
# PASO 7 - CASOS LÍMITE: RESPONSABILIDAD FAMILIAR
# ==========================================================

print("EDADES SIN DATOS:")
print(df_derivadas["Edad"].isna().sum())

print("\nNÚMERO DE HIJOS SIN DATOS:")
print(df_derivadas["Nombre_fills"].isna().sum())

print("\nEDADES FUERA DEL RANGO 18-100:")
print(
    (
        (df_derivadas["Edad"] < 18) |
        (df_derivadas["Edad"] > 100)
    ).sum()
)

print("\nPESOS FAMILIARES NO CALCULADOS:")
print(df_derivadas["Peso_responsabilidad_familiar"].isna().sum())

EDADES SIN DATOS:
77

NÚMERO DE HIJOS SIN DATOS:
32

EDADES FUERA DEL RANGO 18-100:
0

PESOS FAMILIARES NO CALCULADOS:
108

In [ ]:
 faltan datos de edad o de número de hijos. Algunos empleados pueden tener ambas variables vacías, por lo que no debemos sumar directamente 77 + 32 para obtener el total.
Además, las edades incoherentes ya se habían convertido en NaN durante la limpieza anterior. Por eso ahora aparecen cero edades fuera del rango permitido.

In [ ]:
Exercici 4: Exportació i síntesi de resultats
🎯 Objectiu: consolidar els resultats obtinguts després de la preparació, enriquiment i creació de variables, i generar sortides estructurades reutilitzables per a anàlisi o reporting.

In [ ]:
 Utilitzant un bucle, exportar en 4 fitxers (format .csv o .xlsx) les dades corresponents a cada Grup Professional. Per exemple: dades_GrupA.csv, dades_GrupB.csv...
» Crear i exportar un cinquè DataFrame (format .csv o .xlsx) que contingui, per a cada Grup Professional:
Nombre total de treballadors.
Salari mitjà.
Edat mediana.

In [106]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 4
# PASO 1 - COMPROBAR GRUPOS PROFESIONALES
# ==========================================================

# Mostrar los grupos profesionales existentes
print("GRUPOS PROFESIONALES:")
print(df_derivadas["Grup Professional"].unique())

# Contar trabajadores por grupo
print("\nNÚMERO DE TRABAJADORES POR GRUPO:")
print(df_derivadas["Grup Professional"].value_counts())

# Comprobar las dimensiones del dataset
print("\nDIMENSIONES DEL DATASET:")
print(df_derivadas.shape)

GRUPOS PROFESIONALES:
['Grup B' 'Grup C' 'Grup A' 'Grup D']

NÚMERO DE TRABAJADORES POR GRUPO:
Grup Professional
Grup A    456
Grup B    350
Grup C    139
Grup D     40
Name: count, dtype: int64

DIMENSIONES DEL DATASET:
(985, 36)

In [107]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 4
# PASO 2 - EXPORTAR GRUPOS PROFESIONALES A CSV
# ==========================================================

# Lista de grupos profesionales
grupos = ["Grup A", "Grup B", "Grup C", "Grup D"]

# Recorrer los grupos con un bucle
for grupo in grupos:

    # Filtrar los trabajadores de cada grupo
    df_grupo = df_derivadas[
        df_derivadas["Grup Professional"] == grupo
    ]

    # Crear el nombre del archivo
    nombre_archivo = "datos_" + grupo.replace(" ", "") + ".csv"

    # Exportar el archivo CSV
    df_grupo.to_csv(nombre_archivo, index=False, encoding="utf-8-sig")

    # Mostrar confirmación
    print(nombre_archivo, ":", len(df_grupo), "trabajadores")

datos_GrupA.csv : 456 trabajadores
datos_GrupB.csv : 350 trabajadores
datos_GrupC.csv : 139 trabajadores
datos_GrupD.csv : 40 trabajadores

In [108]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 4
# PASO 3 - CREAR Y EXPORTAR EL RESUMEN
# ==========================================================

# Agrupar los datos por grupo profesional
df_resumen = df_derivadas.groupby("Grup Professional").agg(
    Total_trabajadores=("DNI", "count"),
    Salario_medio=("Salari mensual", "mean"),
    Edad_mediana=("Edad", "median")
).reset_index()

# Redondear el salario medio a dos decimales / Media: suma todos los valores y los divide entre el número de observaciones válidas.
df_resumen["Salario_medio"] = df_resumen["Salario_medio"].round(2)

# Exportar el quinto archivo CSV
df_resumen.to_csv(
    "resumen_grupos.csv",
    index=False,
    encoding="utf-8-sig"
)

# Mostrar el resultado con formato de euros / Mediana: es el valor central cuando ordenamos los datos de menor a mayor. Es menos sensible a valores extremos.
display(
    df_resumen.style.format({
        "Salario_medio": "{:,.2f} €",
        "Edad_mediana": "{:.0f}"
    }, na_rep="—")
)

print("Archivo creado: resumen_grupos.csv")

Archivo creado: resumen_grupos.csv

In [109]:
# ==========================================================
# SPRINT 8 - NIVEL 2 - EJERCICIO 4
# PASO 4 - EXPORTAR TODO A UN EXCEL
# ==========================================================

# Crear un archivo Excel con varias pestañas
with pd.ExcelWriter("resultados_sprint8.xlsx") as writer:

    # Crear una pestaña para cada grupo profesional
    for grupo in grupos:

        df_grupo = df_derivadas[
            df_derivadas["Grup Professional"] == grupo
        ]

        # Nombre de la pestaña
        nombre_hoja = grupo.replace(" ", "")

        # Guardar el grupo en su pestaña
        df_grupo.to_excel(
            writer,
            sheet_name=nombre_hoja,
            index=False
        )

    # Crear la pestaña del resumen
    df_resumen.to_excel(
        writer,
        sheet_name="Resumen",
        index=False
    )

print("Archivo Excel creado: resultados_sprint8.xlsx")

Archivo Excel creado: resultados_sprint8.xlsx

In [110]:
from google.colab import files

files.download("resultados_sprint8.xlsx")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
He  organizado y exportado los datos de 985 trabajadores, utilizando un bucle for para generar cuatro archivos CSV, uno por cada grupo profesional.

También he creado un DataFrame resumen mediante groupby() y agg(), calculando el número de trabajadores, el salario medio y la edad mediana de cada grupo.

Los resultados muestran que el Grup D tiene el salario medio más alto (2.811,08 €), mientras que el Grup A presenta el más bajo (1.022,60 €).

Finalmente, he utilizado ExcelWriter() para guardar los cinco DataFrames en un único archivo Excel con pestañas independientes.